--
-- PostgreSQL database dump
--

\restrict WFthLd5e1ujJg5waMlCqdASOfdeACEYJsp36vmMNd1IzO9KabO5v8GixURuGX2C

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-04-23 21:33:31

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16643)
-- Name: alert; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.alert (
    id bigint NOT NULL,
    affected_shipment_ids character varying(255),
    alert_type character varying(255),
    messsage character varying(255),
    node_name character varying(255),
    severity integer NOT NULL,
    status character varying(255),
    "time" timestamp(6) without time zone,
    admin_id bigint,
    CONSTRAINT alert_status_check CHECK (((status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('ACCEPTED'::character varying)::text, ('DISMISSED'::character varying)::text])))
);


ALTER TABLE public.alert OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16651)
-- Name: alert_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.alert ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alert_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16652)
-- Name: driver_location; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.driver_location (
    id bigint NOT NULL,
    available boolean DEFAULT true,
    driver_id character varying(255),
    last_updated timestamp(6) without time zone,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL
);


ALTER TABLE public.driver_location OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16659)
-- Name: driver_location_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.driver_location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.driver_location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16660)
-- Name: route_option; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.route_option (
    id bigint NOT NULL,
    estimated_hours integer NOT NULL,
    label character varying(255),
    path character varying(255),
    risk_level character varying(255),
    status character varying(255),
    tradeoff character varying(255),
    alert_id bigint,
    CONSTRAINT route_option_status_check CHECK (((status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('SELECTED'::character varying)::text, ('REJECTED'::character varying)::text])))
);


ALTER TABLE public.route_option OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16668)
-- Name: route_option_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.route_option ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.route_option_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16669)
-- Name: routes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.routes (
    id bigint NOT NULL,
    distance double precision NOT NULL,
    estimated_time character varying(255),
    path text,
    priority integer NOT NULL,
    risk_level character varying(255),
    status character varying(255),
    destination_id bigint,
    source_id bigint
);


ALTER TABLE public.routes OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16677)
-- Name: routes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.routes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.routes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16678)
-- Name: shipment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shipment (
    id bigint NOT NULL,
    assigned_driver_id character varying(255),
    assignment_status character varying(255),
    current_path text,
    notes character varying(255),
    priority character varying(255),
    route_nodes text,
    route_status character varying(255),
    status character varying(255),
    route_id bigint,
    transport_id bigint,
    warehouse_id bigint,
    active_route_option_id bigint
);


ALTER TABLE public.shipment OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16684)
-- Name: shipment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shipment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16685)
-- Name: transit_node; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transit_node (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL
);


ALTER TABLE public.transit_node OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16692)
-- Name: transit_node_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.transit_node_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.transit_node_id_seq OWNER TO postgres;

--
-- TOC entry 5103 (class 0 OID 0)
-- Dependencies: 230
-- Name: transit_node_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.transit_node_id_seq OWNED BY public.transit_node.id;


--
-- TOC entry 231 (class 1259 OID 16693)
-- Name: transport; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transport (
    id bigint NOT NULL,
    current_location character varying(255),
    current_route_id character varying(255),
    transport_id character varying(255),
    transport_status character varying(255),
    driver_id bigint
);


ALTER TABLE public.transport OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16699)
-- Name: transport_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transport ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transport_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16700)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    username character varying(255),
    password character varying(255),
    role character varying(255),
    name character varying(255),
    warehouse_id bigint,
    driver_id character varying(255),
    email character varying(255),
    pin character varying(255),
    city character varying(255),
    latitude double precision,
    longitude double precision
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16706)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO postgres;

--
-- TOC entry 5104 (class 0 OID 0)
-- Dependencies: 234
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- TOC entry 235 (class 1259 OID 16707)
-- Name: warehouse; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.warehouse (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    city character varying(255),
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    admin_user_id bigint
);


ALTER TABLE public.warehouse OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16716)
-- Name: warehouse_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.warehouse_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.warehouse_id_seq OWNER TO postgres;

--
-- TOC entry 5105 (class 0 OID 0)
-- Dependencies: 236
-- Name: warehouse_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.warehouse_id_seq OWNED BY public.warehouse.id;


--
-- TOC entry 4897 (class 2604 OID 16717)
-- Name: transit_node id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transit_node ALTER COLUMN id SET DEFAULT nextval('public.transit_node_id_seq'::regclass);


--
-- TOC entry 4898 (class 2604 OID 16718)
-- Name: users id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- TOC entry 4899 (class 2604 OID 16719)
-- Name: warehouse id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse ALTER COLUMN id SET DEFAULT nextval('public.warehouse_id_seq'::regclass);


--
-- TOC entry 5080 (class 0 OID 16643)
-- Dependencies: 219
-- Data for Name: alert; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.alert (id, affected_shipment_ids, alert_type, messsage, node_name, severity, status, "time", admin_id) FROM stdin;
20	11,12	WEATHER	MOCK ALERT: Severe flooding at Solapur Bypass. Highway closed.	Solapur	90	ACCEPTED	2026-04-23 20:20:17.160999	53
\.


--
-- TOC entry 5082 (class 0 OID 16652)
-- Dependencies: 221
-- Data for Name: driver_location; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.driver_location (id, available, driver_id, last_updated, latitude, longitude) FROM stdin;
12	t	518	2026-04-16 17:17:29.450622	28.6139	77.209
11	t	\N	2026-04-16 17:15:09.327116	19.82577	83.09606
17	t	001	2026-04-16 19:10:04.458421	20.5937	78.9629
18	t	002	2026-04-16 19:11:19.114217	20.5937	78.9629
19	t	003	2026-04-16 19:12:57.340048	20.5937	78.9629
20	t	004	2026-04-16 19:13:59.159358	20.5937	78.9629
21	t	005	2026-04-16 19:15:04.79753	20.5937	78.9629
22	t	006	2026-04-16 19:15:48.598249	20.5937	78.9629
23	t	007	2026-04-16 19:16:36.453565	20.5937	78.9629
24	t	008	2026-04-16 19:17:31.5623	20.5937	78.9629
25	t	009	2026-04-16 19:18:13.286212	20.5937	78.9629
15	t	09	2026-04-16 17:52:38.713512	13.0827	80.2707
28	t	SUB-101	2026-04-16 20:33:07.261619	22.5726	88.3639
9	t	drv666	2026-04-16 12:45:16.482586	22.5958	88.2636
10	t	drv876	2026-04-16 17:14:00.148102	19.076	72.8777
26	t	DEBUG-001	2026-04-16 19:38:18.829294	19.076	72.8777
27	t	100	2026-04-16 20:15:51.76724	19.076	72.8777
16	t	431	2026-04-16 18:13:31.899261	20.5937	78.9629
8	t	DRV-999	2026-04-17 10:03:17.206924	18.5204	73.8567
30	t	vol-1	2026-04-17 10:14:20.504402	23.5204	87.3119
31	t	DUR-7987	2026-04-18 13:41:52.213572	23.5204	87.3119
32	t	AHM-2314	2026-04-18 22:57:07.706262	23.0225	72.5714
35	f	HYD-3593	2026-04-23 01:13:44.691646	17.385	78.4867
36	f	HYD-5231	2026-04-23 10:15:05.422223	17.385	78.4867
13	f	123	2026-04-16 17:48:33.531852	12.9716	77.5946
37	f	BAN-7342	2026-04-23 14:17:48.210433	12.9716	77.5946
29	f	101	2026-04-19 12:38:38.287339	12.45318	77.36565999999999
14	f	564	2026-04-16 17:51:01.160477	17.385	78.4867
33	f	HYD-9593	2026-04-19 12:08:55.08714	17.385	78.4867
34	f	HYD-6262	2026-04-22 20:35:35.447562	17.385	78.4867
\.


--
-- TOC entry 5084 (class 0 OID 16660)
-- Dependencies: 223
-- Data for Name: route_option; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.route_option (id, estimated_hours, label, path, risk_level, status, tradeoff, alert_id) FROM stdin;
5	5	AI Dynamic Reroute	bangalore -> hyderabad	LOW	SELECTED	Bypassed solapur using the safest dynamic connections.	20
\.


--
-- TOC entry 5086 (class 0 OID 16669)
-- Dependencies: 225
-- Data for Name: routes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.routes (id, distance, estimated_time, path, priority, risk_level, status, destination_id, source_id) FROM stdin;
1	381	8 Hours	Bangalore Tech Hub -> Hyderabad Logistics Hub (Direct Express)	1	MEDIUM	ACTIVE	2	1
2	397	8 Hours	Bangalore Tech Hub -> Chennai -> Hyderabad Logistics Hub (Primary)	2	HIGH	ACTIVE	2	1
3	426	9 Hours	Bangalore Tech Hub -> Warangal -> Mysore -> Hyderabad Logistics Hub	3	LOW	ACTIVE	2	1
4	447	9 Hours	Bangalore Tech Hub -> Vellore -> Chennai -> Hyderabad Logistics Hub	4	MEDIUM	ACTIVE	2	1
5	431	9 Hours	Bangalore Tech Hub -> Hubli -> Warangal -> Hyderabad Logistics Hub	5	HIGH	ACTIVE	2	1
6	484	10 Hours	Bangalore Tech Hub -> Chennai -> Mysore -> Hyderabad Logistics Hub	6	LOW	ACTIVE	2	1
7	499	10 Hours	Bangalore Tech Hub -> Warangal -> Solapur -> Hyderabad Logistics Hub	7	MEDIUM	ACTIVE	2	1
8	494	10 Hours	Bangalore Tech Hub -> Vellore -> Warangal -> Hyderabad Logistics Hub	8	HIGH	ACTIVE	2	1
9	532	10 Hours	Bangalore Tech Hub -> Hubli -> Mysore -> Hyderabad Logistics Hub	9	LOW	ACTIVE	2	1
10	503	10 Hours	Bangalore Tech Hub -> Chennai -> Solapur -> Hyderabad Logistics Hub	10	MEDIUM	ACTIVE	2	1
11	597	11 Hours	Bangalore Tech Hub -> Chennai Port Warehouse (Direct Express)	1	MEDIUM	ACTIVE	3	1
12	597	11 Hours	Bangalore Tech Hub -> Mysore -> Chennai Port Warehouse (Primary)	2	HIGH	ACTIVE	3	1
13	615	12 Hours	Bangalore Tech Hub -> Coimbatore -> Madurai -> Chennai Port Warehouse	3	LOW	ACTIVE	3	1
14	633	12 Hours	Bangalore Tech Hub -> Vellore -> Mysore -> Chennai Port Warehouse	4	MEDIUM	ACTIVE	3	1
15	649	12 Hours	Bangalore Tech Hub -> Salem -> Coimbatore -> Chennai Port Warehouse	5	HIGH	ACTIVE	3	1
16	652	12 Hours	Bangalore Tech Hub -> Mysore -> Madurai -> Chennai Port Warehouse	6	LOW	ACTIVE	3	1
17	658	12 Hours	Bangalore Tech Hub -> Coimbatore -> Kozhikode -> Chennai Port Warehouse	7	MEDIUM	ACTIVE	3	1
18	671	13 Hours	Bangalore Tech Hub -> Vellore -> Coimbatore -> Chennai Port Warehouse	8	HIGH	ACTIVE	3	1
19	720	14 Hours	Bangalore Tech Hub -> Salem -> Madurai -> Chennai Port Warehouse	9	LOW	ACTIVE	3	1
20	719	13 Hours	Bangalore Tech Hub -> Mysore -> Kozhikode -> Chennai Port Warehouse	10	MEDIUM	ACTIVE	3	1
21	813	15 Hours	Bangalore Tech Hub -> Kolkata East Hub (Direct Express)	1	MEDIUM	ACTIVE	4	1
22	821	15 Hours	Bangalore Tech Hub -> Cuttack -> Kolkata East Hub (Primary)	2	HIGH	ACTIVE	4	1
23	836	15 Hours	Bangalore Tech Hub -> Hyderabad -> Nizamabad -> Kolkata East Hub	3	LOW	ACTIVE	4	1
24	824	15 Hours	Bangalore Tech Hub -> Warangal -> Cuttack -> Kolkata East Hub	4	MEDIUM	ACTIVE	4	1
25	849	16 Hours	Bangalore Tech Hub -> Bhubaneswar -> Hyderabad -> Kolkata East Hub	5	HIGH	ACTIVE	4	1
26	840	16 Hours	Bangalore Tech Hub -> Cuttack -> Nizamabad -> Kolkata East Hub	6	LOW	ACTIVE	4	1
27	889	16 Hours	Bangalore Tech Hub -> Hyderabad -> Nagpur -> Kolkata East Hub	7	MEDIUM	ACTIVE	4	1
28	910	17 Hours	Bangalore Tech Hub -> Warangal -> Hyderabad -> Kolkata East Hub	8	HIGH	ACTIVE	4	1
29	892	16 Hours	Bangalore Tech Hub -> Bhubaneswar -> Nizamabad -> Kolkata East Hub	9	LOW	ACTIVE	4	1
30	907	17 Hours	Bangalore Tech Hub -> Cuttack -> Nagpur -> Kolkata East Hub	10	MEDIUM	ACTIVE	4	1
31	1002	18 Hours	Bangalore Tech Hub -> Pune Distribution Center (Direct Express)	1	MEDIUM	ACTIVE	5	1
32	1009	18 Hours	Bangalore Tech Hub -> Kolhapur -> Pune Distribution Center (Primary)	2	HIGH	ACTIVE	5	1
33	1031	19 Hours	Bangalore Tech Hub -> Solapur -> Mangalore -> Pune Distribution Center	3	LOW	ACTIVE	5	1
34	1026	19 Hours	Bangalore Tech Hub -> Hubli -> Kolhapur -> Pune Distribution Center	4	MEDIUM	ACTIVE	5	1
35	1038	19 Hours	Bangalore Tech Hub -> Belgaum -> Solapur -> Pune Distribution Center	5	HIGH	ACTIVE	5	1
36	1075	19 Hours	Bangalore Tech Hub -> Kolhapur -> Mangalore -> Pune Distribution Center	6	LOW	ACTIVE	5	1
37	1058	19 Hours	Bangalore Tech Hub -> Solapur -> Hyderabad -> Pune Distribution Center	7	MEDIUM	ACTIVE	5	1
38	1073	19 Hours	Bangalore Tech Hub -> Hubli -> Solapur -> Pune Distribution Center	8	HIGH	ACTIVE	5	1
39	1088	20 Hours	Bangalore Tech Hub -> Belgaum -> Mangalore -> Pune Distribution Center	9	LOW	ACTIVE	5	1
40	1147	21 Hours	Bangalore Tech Hub -> Kolhapur -> Hyderabad -> Pune Distribution Center	10	MEDIUM	ACTIVE	5	1
41	1171	21 Hours	Bangalore Tech Hub -> Ahmedabad Trade Hub (Direct Express)	1	MEDIUM	ACTIVE	6	1
42	1202	22 Hours	Bangalore Tech Hub -> Kolhapur -> Ahmedabad Trade Hub (Primary)	2	HIGH	ACTIVE	6	1
43	1227	22 Hours	Bangalore Tech Hub -> Lonavala -> Aurangabad -> Ahmedabad Trade Hub	3	LOW	ACTIVE	6	1
44	1243	22 Hours	Bangalore Tech Hub -> Solapur -> Kolhapur -> Ahmedabad Trade Hub	4	MEDIUM	ACTIVE	6	1
45	1273	23 Hours	Bangalore Tech Hub -> Pune -> Lonavala -> Ahmedabad Trade Hub	5	HIGH	ACTIVE	6	1
46	1284	23 Hours	Bangalore Tech Hub -> Kolhapur -> Aurangabad -> Ahmedabad Trade Hub	6	LOW	ACTIVE	6	1
47	1296	23 Hours	Bangalore Tech Hub -> Lonavala -> Belgaum -> Ahmedabad Trade Hub	7	MEDIUM	ACTIVE	6	1
48	1301	23 Hours	Bangalore Tech Hub -> Solapur -> Lonavala -> Ahmedabad Trade Hub	8	HIGH	ACTIVE	6	1
49	1310	23 Hours	Bangalore Tech Hub -> Pune -> Aurangabad -> Ahmedabad Trade Hub	9	LOW	ACTIVE	6	1
50	1322	24 Hours	Bangalore Tech Hub -> Kolhapur -> Belgaum -> Ahmedabad Trade Hub	10	MEDIUM	ACTIVE	6	1
51	1387	25 Hours	Bangalore Tech Hub -> Jaipur Regional Hub (Direct Express)	1	MEDIUM	ACTIVE	7	1
52	1399	25 Hours	Bangalore Tech Hub -> Nizamabad -> Jaipur Regional Hub (Primary)	2	HIGH	ACTIVE	7	1
53	1443	26 Hours	Bangalore Tech Hub -> Solapur -> Nagpur -> Jaipur Regional Hub	3	LOW	ACTIVE	7	1
54	1440	26 Hours	Bangalore Tech Hub -> Aurangabad -> Nizamabad -> Jaipur Regional Hub	4	MEDIUM	ACTIVE	7	1
55	1459	26 Hours	Bangalore Tech Hub -> Amravati -> Solapur -> Jaipur Regional Hub	5	HIGH	ACTIVE	7	1
56	1468	26 Hours	Bangalore Tech Hub -> Nizamabad -> Nagpur -> Jaipur Regional Hub	6	LOW	ACTIVE	7	1
57	1498	26 Hours	Bangalore Tech Hub -> Solapur -> Indore -> Jaipur Regional Hub	7	MEDIUM	ACTIVE	7	1
58	1499	26 Hours	Bangalore Tech Hub -> Aurangabad -> Solapur -> Jaipur Regional Hub	8	HIGH	ACTIVE	7	1
59	1509	27 Hours	Bangalore Tech Hub -> Amravati -> Nagpur -> Jaipur Regional Hub	9	LOW	ACTIVE	7	1
60	1517	27 Hours	Bangalore Tech Hub -> Nizamabad -> Indore -> Jaipur Regional Hub	10	MEDIUM	ACTIVE	7	1
61	1581	28 Hours	Bangalore Tech Hub -> Lucknow Supply Center (Direct Express)	1	MEDIUM	ACTIVE	8	1
62	1621	29 Hours	Bangalore Tech Hub -> Amravati -> Lucknow Supply Center (Primary)	2	HIGH	ACTIVE	8	1
63	1611	28 Hours	Bangalore Tech Hub -> Warangal -> Hyderabad -> Lucknow Supply Center	3	LOW	ACTIVE	8	1
64	1650	29 Hours	Bangalore Tech Hub -> Nagpur -> Amravati -> Lucknow Supply Center	4	MEDIUM	ACTIVE	8	1
65	1628	29 Hours	Bangalore Tech Hub -> Nizamabad -> Warangal -> Lucknow Supply Center	5	HIGH	ACTIVE	8	1
66	1689	30 Hours	Bangalore Tech Hub -> Amravati -> Hyderabad -> Lucknow Supply Center	6	LOW	ACTIVE	8	1
67	1685	30 Hours	Bangalore Tech Hub -> Warangal -> Jabalpur -> Lucknow Supply Center	7	MEDIUM	ACTIVE	8	1
68	1690	30 Hours	Bangalore Tech Hub -> Nagpur -> Warangal -> Lucknow Supply Center	8	HIGH	ACTIVE	8	1
69	1710	30 Hours	Bangalore Tech Hub -> Nizamabad -> Hyderabad -> Lucknow Supply Center	9	LOW	ACTIVE	8	1
70	1728	30 Hours	Bangalore Tech Hub -> Amravati -> Jabalpur -> Lucknow Supply Center	10	MEDIUM	ACTIVE	8	1
71	376	8 Hours	Hyderabad Logistics Hub -> Bangalore Tech Hub (Direct Express)	1	MEDIUM	ACTIVE	1	2
72	408	8 Hours	Hyderabad Logistics Hub -> Chennai -> Bangalore Tech Hub (Primary)	2	HIGH	ACTIVE	1	2
73	441	9 Hours	Hyderabad Logistics Hub -> Warangal -> Mysore -> Bangalore Tech Hub	3	LOW	ACTIVE	1	2
74	445	9 Hours	Hyderabad Logistics Hub -> Vellore -> Chennai -> Bangalore Tech Hub	4	MEDIUM	ACTIVE	1	2
75	429	9 Hours	Hyderabad Logistics Hub -> Hubli -> Warangal -> Bangalore Tech Hub	5	HIGH	ACTIVE	1	2
76	458	9 Hours	Hyderabad Logistics Hub -> Chennai -> Mysore -> Bangalore Tech Hub	6	LOW	ACTIVE	1	2
77	498	10 Hours	Hyderabad Logistics Hub -> Warangal -> Solapur -> Bangalore Tech Hub	7	MEDIUM	ACTIVE	1	2
78	474	9 Hours	Hyderabad Logistics Hub -> Vellore -> Warangal -> Bangalore Tech Hub	8	HIGH	ACTIVE	1	2
79	498	10 Hours	Hyderabad Logistics Hub -> Hubli -> Mysore -> Bangalore Tech Hub	9	LOW	ACTIVE	1	2
80	529	10 Hours	Hyderabad Logistics Hub -> Chennai -> Solapur -> Bangalore Tech Hub	10	MEDIUM	ACTIVE	1	2
81	389	8 Hours	Hyderabad Logistics Hub -> Chennai Port Warehouse (Direct Express)	1	MEDIUM	ACTIVE	3	2
82	419	8 Hours	Hyderabad Logistics Hub -> Bangalore -> Chennai Port Warehouse (Primary)	2	HIGH	ACTIVE	3	2
83	414	8 Hours	Hyderabad Logistics Hub -> Nizamabad -> Salem -> Chennai Port Warehouse	3	LOW	ACTIVE	3	2
84	459	9 Hours	Hyderabad Logistics Hub -> Vellore -> Bangalore -> Chennai Port Warehouse	4	MEDIUM	ACTIVE	3	2
85	431	9 Hours	Hyderabad Logistics Hub -> Warangal -> Nizamabad -> Chennai Port Warehouse	5	HIGH	ACTIVE	3	2
86	447	9 Hours	Hyderabad Logistics Hub -> Bangalore -> Salem -> Chennai Port Warehouse	6	LOW	ACTIVE	3	2
87	470	9 Hours	Hyderabad Logistics Hub -> Nizamabad -> Mysore -> Chennai Port Warehouse	7	MEDIUM	ACTIVE	3	2
88	508	10 Hours	Hyderabad Logistics Hub -> Vellore -> Nizamabad -> Chennai Port Warehouse	8	HIGH	ACTIVE	3	2
89	521	10 Hours	Hyderabad Logistics Hub -> Warangal -> Salem -> Chennai Port Warehouse	9	LOW	ACTIVE	3	2
90	548	11 Hours	Hyderabad Logistics Hub -> Bangalore -> Mysore -> Chennai Port Warehouse	10	MEDIUM	ACTIVE	3	2
91	589	11 Hours	Hyderabad Logistics Hub -> Kolkata East Hub (Direct Express)	1	MEDIUM	ACTIVE	4	2
92	580	11 Hours	Hyderabad Logistics Hub -> Warangal -> Kolkata East Hub (Primary)	2	HIGH	ACTIVE	4	2
93	622	12 Hours	Hyderabad Logistics Hub -> Nagpur -> Jabalpur -> Kolkata East Hub	3	LOW	ACTIVE	4	2
94	613	12 Hours	Hyderabad Logistics Hub -> Bhubaneswar -> Warangal -> Kolkata East Hub	4	MEDIUM	ACTIVE	4	2
95	670	13 Hours	Hyderabad Logistics Hub -> Cuttack -> Nagpur -> Kolkata East Hub	5	HIGH	ACTIVE	4	2
96	676	13 Hours	Hyderabad Logistics Hub -> Warangal -> Jabalpur -> Kolkata East Hub	6	LOW	ACTIVE	4	2
97	698	13 Hours	Hyderabad Logistics Hub -> Nagpur -> Gaya -> Kolkata East Hub	7	MEDIUM	ACTIVE	4	2
98	670	13 Hours	Hyderabad Logistics Hub -> Bhubaneswar -> Nagpur -> Kolkata East Hub	8	HIGH	ACTIVE	4	2
99	720	14 Hours	Hyderabad Logistics Hub -> Cuttack -> Jabalpur -> Kolkata East Hub	9	LOW	ACTIVE	4	2
100	722	14 Hours	Hyderabad Logistics Hub -> Warangal -> Gaya -> Kolkata East Hub	10	MEDIUM	ACTIVE	4	2
101	768	14 Hours	Hyderabad Logistics Hub -> Pune Distribution Center (Direct Express)	1	MEDIUM	ACTIVE	5	2
102	817	15 Hours	Hyderabad Logistics Hub -> Aurangabad -> Pune Distribution Center (Primary)	2	HIGH	ACTIVE	5	2
103	823	15 Hours	Hyderabad Logistics Hub -> Kolhapur -> Belgaum -> Pune Distribution Center	3	LOW	ACTIVE	5	2
104	822	15 Hours	Hyderabad Logistics Hub -> Solapur -> Aurangabad -> Pune Distribution Center	4	MEDIUM	ACTIVE	5	2
105	859	16 Hours	Hyderabad Logistics Hub -> Nizamabad -> Kolhapur -> Pune Distribution Center	5	HIGH	ACTIVE	5	2
106	879	16 Hours	Hyderabad Logistics Hub -> Aurangabad -> Belgaum -> Pune Distribution Center	6	LOW	ACTIVE	5	2
107	855	16 Hours	Hyderabad Logistics Hub -> Kolhapur -> Hubli -> Pune Distribution Center	7	MEDIUM	ACTIVE	5	2
108	883	16 Hours	Hyderabad Logistics Hub -> Solapur -> Kolhapur -> Pune Distribution Center	8	HIGH	ACTIVE	5	2
109	917	17 Hours	Hyderabad Logistics Hub -> Nizamabad -> Belgaum -> Pune Distribution Center	9	LOW	ACTIVE	5	2
110	916	17 Hours	Hyderabad Logistics Hub -> Aurangabad -> Hubli -> Pune Distribution Center	10	MEDIUM	ACTIVE	5	2
111	990	18 Hours	Hyderabad Logistics Hub -> Ahmedabad Trade Hub (Direct Express)	1	MEDIUM	ACTIVE	6	2
112	1011	18 Hours	Hyderabad Logistics Hub -> Amravati -> Ahmedabad Trade Hub (Primary)	2	HIGH	ACTIVE	6	2
113	1017	18 Hours	Hyderabad Logistics Hub -> Pune -> Indore -> Ahmedabad Trade Hub	3	LOW	ACTIVE	6	2
114	1026	19 Hours	Hyderabad Logistics Hub -> Aurangabad -> Amravati -> Ahmedabad Trade Hub	4	MEDIUM	ACTIVE	6	2
115	1043	19 Hours	Hyderabad Logistics Hub -> Nasik -> Pune -> Ahmedabad Trade Hub	5	HIGH	ACTIVE	6	2
116	1041	19 Hours	Hyderabad Logistics Hub -> Amravati -> Indore -> Ahmedabad Trade Hub	6	LOW	ACTIVE	6	2
117	1055	19 Hours	Hyderabad Logistics Hub -> Pune -> Lonavala -> Ahmedabad Trade Hub	7	MEDIUM	ACTIVE	6	2
118	1118	20 Hours	Hyderabad Logistics Hub -> Aurangabad -> Pune -> Ahmedabad Trade Hub	8	HIGH	ACTIVE	6	2
119	1105	20 Hours	Hyderabad Logistics Hub -> Nasik -> Indore -> Ahmedabad Trade Hub	9	LOW	ACTIVE	6	2
120	1143	21 Hours	Hyderabad Logistics Hub -> Amravati -> Lonavala -> Ahmedabad Trade Hub	10	MEDIUM	ACTIVE	6	2
121	1211	22 Hours	Hyderabad Logistics Hub -> Jaipur Regional Hub (Direct Express)	1	MEDIUM	ACTIVE	7	2
122	1208	22 Hours	Hyderabad Logistics Hub -> Indore -> Jaipur Regional Hub (Primary)	2	HIGH	ACTIVE	7	2
123	1204	22 Hours	Hyderabad Logistics Hub -> Nagpur -> Aurangabad -> Jaipur Regional Hub	3	LOW	ACTIVE	7	2
124	1211	22 Hours	Hyderabad Logistics Hub -> Bhopal -> Indore -> Jaipur Regional Hub	4	MEDIUM	ACTIVE	7	2
125	1272	23 Hours	Hyderabad Logistics Hub -> Amravati -> Nagpur -> Jaipur Regional Hub	5	HIGH	ACTIVE	7	2
126	1241	22 Hours	Hyderabad Logistics Hub -> Indore -> Aurangabad -> Jaipur Regional Hub	6	LOW	ACTIVE	7	2
127	1263	23 Hours	Hyderabad Logistics Hub -> Nagpur -> Jabalpur -> Jaipur Regional Hub	7	MEDIUM	ACTIVE	7	2
128	1286	23 Hours	Hyderabad Logistics Hub -> Bhopal -> Nagpur -> Jaipur Regional Hub	8	HIGH	ACTIVE	7	2
129	1321	24 Hours	Hyderabad Logistics Hub -> Amravati -> Aurangabad -> Jaipur Regional Hub	9	LOW	ACTIVE	7	2
130	1311	23 Hours	Hyderabad Logistics Hub -> Indore -> Jabalpur -> Jaipur Regional Hub	10	MEDIUM	ACTIVE	7	2
131	1410	25 Hours	Hyderabad Logistics Hub -> Lucknow Supply Center (Direct Express)	1	MEDIUM	ACTIVE	8	2
132	1381	25 Hours	Hyderabad Logistics Hub -> Amravati -> Lucknow Supply Center (Primary)	2	HIGH	ACTIVE	8	2
133	1402	25 Hours	Hyderabad Logistics Hub -> Bhopal -> Nizamabad -> Lucknow Supply Center	3	LOW	ACTIVE	8	2
134	1449	26 Hours	Hyderabad Logistics Hub -> Jabalpur -> Amravati -> Lucknow Supply Center	4	MEDIUM	ACTIVE	8	2
135	1426	25 Hours	Hyderabad Logistics Hub -> Nagpur -> Bhopal -> Lucknow Supply Center	5	HIGH	ACTIVE	8	2
136	1469	26 Hours	Hyderabad Logistics Hub -> Amravati -> Nizamabad -> Lucknow Supply Center	6	LOW	ACTIVE	8	2
137	1480	26 Hours	Hyderabad Logistics Hub -> Bhopal -> Indore -> Lucknow Supply Center	7	MEDIUM	ACTIVE	8	2
138	1512	27 Hours	Hyderabad Logistics Hub -> Jabalpur -> Bhopal -> Lucknow Supply Center	8	HIGH	ACTIVE	8	2
139	1528	27 Hours	Hyderabad Logistics Hub -> Nagpur -> Nizamabad -> Lucknow Supply Center	9	LOW	ACTIVE	8	2
140	1537	27 Hours	Hyderabad Logistics Hub -> Amravati -> Indore -> Lucknow Supply Center	10	MEDIUM	ACTIVE	8	2
141	609	12 Hours	Chennai Port Warehouse -> Bangalore Tech Hub (Direct Express)	1	MEDIUM	ACTIVE	1	3
142	580	11 Hours	Chennai Port Warehouse -> Mysore -> Bangalore Tech Hub (Primary)	2	HIGH	ACTIVE	1	3
143	640	12 Hours	Chennai Port Warehouse -> Coimbatore -> Madurai -> Bangalore Tech Hub	3	LOW	ACTIVE	1	3
144	651	12 Hours	Chennai Port Warehouse -> Vellore -> Mysore -> Bangalore Tech Hub	4	MEDIUM	ACTIVE	1	3
145	626	12 Hours	Chennai Port Warehouse -> Salem -> Coimbatore -> Bangalore Tech Hub	5	HIGH	ACTIVE	1	3
146	676	13 Hours	Chennai Port Warehouse -> Mysore -> Madurai -> Bangalore Tech Hub	6	LOW	ACTIVE	1	3
147	656	12 Hours	Chennai Port Warehouse -> Coimbatore -> Kozhikode -> Bangalore Tech Hub	7	MEDIUM	ACTIVE	1	3
148	686	13 Hours	Chennai Port Warehouse -> Vellore -> Coimbatore -> Bangalore Tech Hub	8	HIGH	ACTIVE	1	3
149	728	14 Hours	Chennai Port Warehouse -> Salem -> Madurai -> Bangalore Tech Hub	9	LOW	ACTIVE	1	3
150	705	13 Hours	Chennai Port Warehouse -> Mysore -> Kozhikode -> Bangalore Tech Hub	10	MEDIUM	ACTIVE	1	3
151	384	8 Hours	Chennai Port Warehouse -> Hyderabad Logistics Hub (Direct Express)	1	MEDIUM	ACTIVE	2	3
152	382	8 Hours	Chennai Port Warehouse -> Bangalore -> Hyderabad Logistics Hub (Primary)	2	HIGH	ACTIVE	2	3
153	420	9 Hours	Chennai Port Warehouse -> Nizamabad -> Salem -> Hyderabad Logistics Hub	3	LOW	ACTIVE	2	3
154	449	9 Hours	Chennai Port Warehouse -> Vellore -> Bangalore -> Hyderabad Logistics Hub	4	MEDIUM	ACTIVE	2	3
155	434	9 Hours	Chennai Port Warehouse -> Warangal -> Nizamabad -> Hyderabad Logistics Hub	5	HIGH	ACTIVE	2	3
156	485	10 Hours	Chennai Port Warehouse -> Bangalore -> Salem -> Hyderabad Logistics Hub	6	LOW	ACTIVE	2	3
157	499	10 Hours	Chennai Port Warehouse -> Nizamabad -> Mysore -> Hyderabad Logistics Hub	7	MEDIUM	ACTIVE	2	3
158	509	10 Hours	Chennai Port Warehouse -> Vellore -> Nizamabad -> Hyderabad Logistics Hub	8	HIGH	ACTIVE	2	3
159	506	10 Hours	Chennai Port Warehouse -> Warangal -> Salem -> Hyderabad Logistics Hub	9	LOW	ACTIVE	2	3
160	522	10 Hours	Chennai Port Warehouse -> Bangalore -> Mysore -> Hyderabad Logistics Hub	10	MEDIUM	ACTIVE	2	3
161	377	8 Hours	Chennai Port Warehouse -> Kolkata East Hub (Direct Express)	1	MEDIUM	ACTIVE	4	3
162	391	8 Hours	Chennai Port Warehouse -> Warangal -> Kolkata East Hub (Primary)	2	HIGH	ACTIVE	4	3
163	427	9 Hours	Chennai Port Warehouse -> Hyderabad -> Nagpur -> Kolkata East Hub	3	LOW	ACTIVE	4	3
164	423	9 Hours	Chennai Port Warehouse -> Bhubaneswar -> Warangal -> Kolkata East Hub	4	MEDIUM	ACTIVE	4	3
165	442	9 Hours	Chennai Port Warehouse -> Cuttack -> Hyderabad -> Kolkata East Hub	5	HIGH	ACTIVE	4	3
166	467	9 Hours	Chennai Port Warehouse -> Warangal -> Nagpur -> Kolkata East Hub	6	LOW	ACTIVE	4	3
167	482	10 Hours	Chennai Port Warehouse -> Hyderabad -> Nizamabad -> Kolkata East Hub	7	MEDIUM	ACTIVE	4	3
168	495	10 Hours	Chennai Port Warehouse -> Bhubaneswar -> Hyderabad -> Kolkata East Hub	8	HIGH	ACTIVE	4	3
169	532	10 Hours	Chennai Port Warehouse -> Cuttack -> Nagpur -> Kolkata East Hub	9	LOW	ACTIVE	4	3
170	533	10 Hours	Chennai Port Warehouse -> Warangal -> Nizamabad -> Kolkata East Hub	10	MEDIUM	ACTIVE	4	3
171	593	11 Hours	Chennai Port Warehouse -> Pune Distribution Center (Direct Express)	1	MEDIUM	ACTIVE	5	3
172	591	11 Hours	Chennai Port Warehouse -> Solapur -> Pune Distribution Center (Primary)	2	HIGH	ACTIVE	5	3
173	641	12 Hours	Chennai Port Warehouse -> Belgaum -> Bangalore -> Pune Distribution Center	3	LOW	ACTIVE	5	3
174	621	12 Hours	Chennai Port Warehouse -> Hubli -> Solapur -> Pune Distribution Center	4	MEDIUM	ACTIVE	5	3
175	673	13 Hours	Chennai Port Warehouse -> Hyderabad -> Belgaum -> Pune Distribution Center	5	HIGH	ACTIVE	5	3
176	652	12 Hours	Chennai Port Warehouse -> Solapur -> Bangalore -> Pune Distribution Center	6	LOW	ACTIVE	5	3
177	676	13 Hours	Chennai Port Warehouse -> Belgaum -> Kolhapur -> Pune Distribution Center	7	MEDIUM	ACTIVE	5	3
178	672	13 Hours	Chennai Port Warehouse -> Hubli -> Belgaum -> Pune Distribution Center	8	HIGH	ACTIVE	5	3
179	700	13 Hours	Chennai Port Warehouse -> Hyderabad -> Bangalore -> Pune Distribution Center	9	LOW	ACTIVE	5	3
180	743	14 Hours	Chennai Port Warehouse -> Solapur -> Kolhapur -> Pune Distribution Center	10	MEDIUM	ACTIVE	5	3
181	766	14 Hours	Chennai Port Warehouse -> Ahmedabad Trade Hub (Direct Express)	1	MEDIUM	ACTIVE	6	3
182	793	15 Hours	Chennai Port Warehouse -> Aurangabad -> Ahmedabad Trade Hub (Primary)	2	HIGH	ACTIVE	6	3
183	812	15 Hours	Chennai Port Warehouse -> Hyderabad -> Kolhapur -> Ahmedabad Trade Hub	3	LOW	ACTIVE	6	3
184	857	16 Hours	Chennai Port Warehouse -> Solapur -> Aurangabad -> Ahmedabad Trade Hub	4	MEDIUM	ACTIVE	6	3
185	840	16 Hours	Chennai Port Warehouse -> Nizamabad -> Hyderabad -> Ahmedabad Trade Hub	5	HIGH	ACTIVE	6	3
186	872	16 Hours	Chennai Port Warehouse -> Aurangabad -> Kolhapur -> Ahmedabad Trade Hub	6	LOW	ACTIVE	6	3
187	865	16 Hours	Chennai Port Warehouse -> Hyderabad -> Pune -> Ahmedabad Trade Hub	7	MEDIUM	ACTIVE	6	3
188	903	17 Hours	Chennai Port Warehouse -> Solapur -> Hyderabad -> Ahmedabad Trade Hub	8	HIGH	ACTIVE	6	3
189	907	17 Hours	Chennai Port Warehouse -> Nizamabad -> Kolhapur -> Ahmedabad Trade Hub	9	LOW	ACTIVE	6	3
190	946	17 Hours	Chennai Port Warehouse -> Aurangabad -> Pune -> Ahmedabad Trade Hub	10	MEDIUM	ACTIVE	6	3
191	999	18 Hours	Chennai Port Warehouse -> Jaipur Regional Hub (Direct Express)	1	MEDIUM	ACTIVE	7	3
192	1023	19 Hours	Chennai Port Warehouse -> Nagpur -> Jaipur Regional Hub (Primary)	2	HIGH	ACTIVE	7	3
193	1007	18 Hours	Chennai Port Warehouse -> Warangal -> Hyderabad -> Jaipur Regional Hub	3	LOW	ACTIVE	7	3
194	1038	19 Hours	Chennai Port Warehouse -> Amravati -> Nagpur -> Jaipur Regional Hub	4	MEDIUM	ACTIVE	7	3
195	1070	19 Hours	Chennai Port Warehouse -> Nizamabad -> Warangal -> Jaipur Regional Hub	5	HIGH	ACTIVE	7	3
196	1061	19 Hours	Chennai Port Warehouse -> Nagpur -> Hyderabad -> Jaipur Regional Hub	6	LOW	ACTIVE	7	3
197	1104	20 Hours	Chennai Port Warehouse -> Warangal -> Aurangabad -> Jaipur Regional Hub	7	MEDIUM	ACTIVE	7	3
198	1071	19 Hours	Chennai Port Warehouse -> Amravati -> Warangal -> Jaipur Regional Hub	8	HIGH	ACTIVE	7	3
199	1109	20 Hours	Chennai Port Warehouse -> Nizamabad -> Hyderabad -> Jaipur Regional Hub	9	LOW	ACTIVE	7	3
200	1120	20 Hours	Chennai Port Warehouse -> Nagpur -> Aurangabad -> Jaipur Regional Hub	10	MEDIUM	ACTIVE	7	3
201	1181	21 Hours	Chennai Port Warehouse -> Lucknow Supply Center (Direct Express)	1	MEDIUM	ACTIVE	8	3
202	1207	22 Hours	Chennai Port Warehouse -> Nizamabad -> Lucknow Supply Center (Primary)	2	HIGH	ACTIVE	8	3
203	1241	22 Hours	Chennai Port Warehouse -> Amravati -> Jabalpur -> Lucknow Supply Center	3	LOW	ACTIVE	8	3
204	1255	22 Hours	Chennai Port Warehouse -> Nagpur -> Nizamabad -> Lucknow Supply Center	4	MEDIUM	ACTIVE	8	3
205	1249	22 Hours	Chennai Port Warehouse -> Warangal -> Amravati -> Lucknow Supply Center	5	HIGH	ACTIVE	8	3
206	1244	22 Hours	Chennai Port Warehouse -> Nizamabad -> Jabalpur -> Lucknow Supply Center	6	LOW	ACTIVE	8	3
207	1276	23 Hours	Chennai Port Warehouse -> Amravati -> Hyderabad -> Lucknow Supply Center	7	MEDIUM	ACTIVE	8	3
208	1279	23 Hours	Chennai Port Warehouse -> Nagpur -> Amravati -> Lucknow Supply Center	8	HIGH	ACTIVE	8	3
209	1330	24 Hours	Chennai Port Warehouse -> Warangal -> Jabalpur -> Lucknow Supply Center	9	LOW	ACTIVE	8	3
210	1324	24 Hours	Chennai Port Warehouse -> Nizamabad -> Hyderabad -> Lucknow Supply Center	10	MEDIUM	ACTIVE	8	3
211	769	14 Hours	Kolkata East Hub -> Bangalore Tech Hub (Direct Express)	1	MEDIUM	ACTIVE	1	4
212	804	15 Hours	Kolkata East Hub -> Cuttack -> Bangalore Tech Hub (Primary)	2	HIGH	ACTIVE	1	4
213	843	16 Hours	Kolkata East Hub -> Hyderabad -> Nizamabad -> Bangalore Tech Hub	3	LOW	ACTIVE	1	4
214	817	15 Hours	Kolkata East Hub -> Warangal -> Cuttack -> Bangalore Tech Hub	4	MEDIUM	ACTIVE	1	4
215	827	15 Hours	Kolkata East Hub -> Bhubaneswar -> Hyderabad -> Bangalore Tech Hub	5	HIGH	ACTIVE	1	4
216	879	16 Hours	Kolkata East Hub -> Cuttack -> Nizamabad -> Bangalore Tech Hub	6	LOW	ACTIVE	1	4
217	872	16 Hours	Kolkata East Hub -> Hyderabad -> Nagpur -> Bangalore Tech Hub	7	MEDIUM	ACTIVE	1	4
218	894	16 Hours	Kolkata East Hub -> Warangal -> Hyderabad -> Bangalore Tech Hub	8	HIGH	ACTIVE	1	4
219	909	17 Hours	Kolkata East Hub -> Bhubaneswar -> Nizamabad -> Bangalore Tech Hub	9	LOW	ACTIVE	1	4
220	924	17 Hours	Kolkata East Hub -> Cuttack -> Nagpur -> Bangalore Tech Hub	10	MEDIUM	ACTIVE	1	4
221	586	11 Hours	Kolkata East Hub -> Hyderabad Logistics Hub (Direct Express)	1	MEDIUM	ACTIVE	2	4
222	616	12 Hours	Kolkata East Hub -> Warangal -> Hyderabad Logistics Hub (Primary)	2	HIGH	ACTIVE	2	4
223	596	11 Hours	Kolkata East Hub -> Nagpur -> Jabalpur -> Hyderabad Logistics Hub	3	LOW	ACTIVE	2	4
224	632	12 Hours	Kolkata East Hub -> Bhubaneswar -> Warangal -> Hyderabad Logistics Hub	4	MEDIUM	ACTIVE	2	4
225	662	13 Hours	Kolkata East Hub -> Cuttack -> Nagpur -> Hyderabad Logistics Hub	5	HIGH	ACTIVE	2	4
226	665	13 Hours	Kolkata East Hub -> Warangal -> Jabalpur -> Hyderabad Logistics Hub	6	LOW	ACTIVE	2	4
227	664	13 Hours	Kolkata East Hub -> Nagpur -> Gaya -> Hyderabad Logistics Hub	7	MEDIUM	ACTIVE	2	4
228	715	13 Hours	Kolkata East Hub -> Bhubaneswar -> Nagpur -> Hyderabad Logistics Hub	8	HIGH	ACTIVE	2	4
229	698	13 Hours	Kolkata East Hub -> Cuttack -> Jabalpur -> Hyderabad Logistics Hub	9	LOW	ACTIVE	2	4
230	739	14 Hours	Kolkata East Hub -> Warangal -> Gaya -> Hyderabad Logistics Hub	10	MEDIUM	ACTIVE	2	4
231	369	8 Hours	Kolkata East Hub -> Chennai Port Warehouse (Direct Express)	1	MEDIUM	ACTIVE	3	4
232	384	8 Hours	Kolkata East Hub -> Warangal -> Chennai Port Warehouse (Primary)	2	HIGH	ACTIVE	3	4
233	401	8 Hours	Kolkata East Hub -> Hyderabad -> Nagpur -> Chennai Port Warehouse	3	LOW	ACTIVE	3	4
234	414	8 Hours	Kolkata East Hub -> Bhubaneswar -> Warangal -> Chennai Port Warehouse	4	MEDIUM	ACTIVE	3	4
235	454	9 Hours	Kolkata East Hub -> Cuttack -> Hyderabad -> Chennai Port Warehouse	5	HIGH	ACTIVE	3	4
236	471	9 Hours	Kolkata East Hub -> Warangal -> Nagpur -> Chennai Port Warehouse	6	LOW	ACTIVE	3	4
237	503	10 Hours	Kolkata East Hub -> Hyderabad -> Nizamabad -> Chennai Port Warehouse	7	MEDIUM	ACTIVE	3	4
238	518	10 Hours	Kolkata East Hub -> Bhubaneswar -> Hyderabad -> Chennai Port Warehouse	8	HIGH	ACTIVE	3	4
239	495	10 Hours	Kolkata East Hub -> Cuttack -> Nagpur -> Chennai Port Warehouse	9	LOW	ACTIVE	3	4
240	506	10 Hours	Kolkata East Hub -> Warangal -> Nizamabad -> Chennai Port Warehouse	10	MEDIUM	ACTIVE	3	4
241	380	8 Hours	Kolkata East Hub -> Pune Distribution Center (Direct Express)	1	MEDIUM	ACTIVE	5	4
242	391	8 Hours	Kolkata East Hub -> Warangal -> Pune Distribution Center (Primary)	2	HIGH	ACTIVE	5	4
243	412	8 Hours	Kolkata East Hub -> Amravati -> Nizamabad -> Pune Distribution Center	3	LOW	ACTIVE	5	4
244	427	9 Hours	Kolkata East Hub -> Nagpur -> Warangal -> Pune Distribution Center	4	MEDIUM	ACTIVE	5	4
245	443	9 Hours	Kolkata East Hub -> Jabalpur -> Amravati -> Pune Distribution Center	5	HIGH	ACTIVE	5	4
246	477	9 Hours	Kolkata East Hub -> Warangal -> Nizamabad -> Pune Distribution Center	6	LOW	ACTIVE	5	4
247	495	10 Hours	Kolkata East Hub -> Amravati -> Hyderabad -> Pune Distribution Center	7	MEDIUM	ACTIVE	5	4
248	474	9 Hours	Kolkata East Hub -> Nagpur -> Amravati -> Pune Distribution Center	8	HIGH	ACTIVE	5	4
249	507	10 Hours	Kolkata East Hub -> Jabalpur -> Nizamabad -> Pune Distribution Center	9	LOW	ACTIVE	5	4
250	543	11 Hours	Kolkata East Hub -> Warangal -> Hyderabad -> Pune Distribution Center	10	MEDIUM	ACTIVE	5	4
251	586	11 Hours	Kolkata East Hub -> Ahmedabad Trade Hub (Direct Express)	1	MEDIUM	ACTIVE	6	4
252	607	12 Hours	Kolkata East Hub -> Prayagraj -> Ahmedabad Trade Hub (Primary)	2	HIGH	ACTIVE	6	4
253	625	12 Hours	Kolkata East Hub -> Bhopal -> Amravati -> Ahmedabad Trade Hub	3	LOW	ACTIVE	6	4
254	652	12 Hours	Kolkata East Hub -> Jabalpur -> Prayagraj -> Ahmedabad Trade Hub	4	MEDIUM	ACTIVE	6	4
255	645	12 Hours	Kolkata East Hub -> Nagpur -> Bhopal -> Ahmedabad Trade Hub	5	HIGH	ACTIVE	6	4
256	667	13 Hours	Kolkata East Hub -> Prayagraj -> Amravati -> Ahmedabad Trade Hub	6	LOW	ACTIVE	6	4
257	700	13 Hours	Kolkata East Hub -> Bhopal -> Varanasi -> Ahmedabad Trade Hub	7	MEDIUM	ACTIVE	6	4
258	682	13 Hours	Kolkata East Hub -> Jabalpur -> Bhopal -> Ahmedabad Trade Hub	8	HIGH	ACTIVE	6	4
259	733	14 Hours	Kolkata East Hub -> Nagpur -> Amravati -> Ahmedabad Trade Hub	9	LOW	ACTIVE	6	4
260	709	13 Hours	Kolkata East Hub -> Prayagraj -> Varanasi -> Ahmedabad Trade Hub	10	MEDIUM	ACTIVE	6	4
261	768	14 Hours	Kolkata East Hub -> Jaipur Regional Hub (Direct Express)	1	MEDIUM	ACTIVE	7	4
262	813	15 Hours	Kolkata East Hub -> Lucknow -> Jaipur Regional Hub (Primary)	2	HIGH	ACTIVE	7	4
263	827	15 Hours	Kolkata East Hub -> Kanpur -> Jabalpur -> Jaipur Regional Hub	3	LOW	ACTIVE	7	4
264	836	15 Hours	Kolkata East Hub -> Prayagraj -> Lucknow -> Jaipur Regional Hub	4	MEDIUM	ACTIVE	7	4
265	841	16 Hours	Kolkata East Hub -> Varanasi -> Kanpur -> Jaipur Regional Hub	5	HIGH	ACTIVE	7	4
266	867	16 Hours	Kolkata East Hub -> Lucknow -> Jabalpur -> Jaipur Regional Hub	6	LOW	ACTIVE	7	4
267	867	16 Hours	Kolkata East Hub -> Kanpur -> Gaya -> Jaipur Regional Hub	7	MEDIUM	ACTIVE	7	4
268	880	16 Hours	Kolkata East Hub -> Prayagraj -> Kanpur -> Jaipur Regional Hub	8	HIGH	ACTIVE	7	4
269	898	16 Hours	Kolkata East Hub -> Varanasi -> Jabalpur -> Jaipur Regional Hub	9	LOW	ACTIVE	7	4
270	925	17 Hours	Kolkata East Hub -> Lucknow -> Gaya -> Jaipur Regional Hub	10	MEDIUM	ACTIVE	7	4
271	993	18 Hours	Kolkata East Hub -> Lucknow Supply Center (Direct Express)	1	MEDIUM	ACTIVE	8	4
272	1015	18 Hours	Kolkata East Hub -> Varanasi -> Lucknow Supply Center (Primary)	2	HIGH	ACTIVE	8	4
273	1019	18 Hours	Kolkata East Hub -> Asansol -> Prayagraj -> Lucknow Supply Center	3	LOW	ACTIVE	8	4
274	1059	19 Hours	Kolkata East Hub -> Gaya -> Varanasi -> Lucknow Supply Center	4	MEDIUM	ACTIVE	8	4
275	1060	19 Hours	Kolkata East Hub -> Patna -> Asansol -> Lucknow Supply Center	5	HIGH	ACTIVE	8	4
276	1043	19 Hours	Kolkata East Hub -> Varanasi -> Prayagraj -> Lucknow Supply Center	6	LOW	ACTIVE	8	4
277	1079	19 Hours	Kolkata East Hub -> Asansol -> Siliguri -> Lucknow Supply Center	7	MEDIUM	ACTIVE	8	4
278	1096	20 Hours	Kolkata East Hub -> Gaya -> Asansol -> Lucknow Supply Center	8	HIGH	ACTIVE	8	4
279	1102	20 Hours	Kolkata East Hub -> Patna -> Prayagraj -> Lucknow Supply Center	9	LOW	ACTIVE	8	4
280	1141	21 Hours	Kolkata East Hub -> Varanasi -> Siliguri -> Lucknow Supply Center	10	MEDIUM	ACTIVE	8	4
281	980	18 Hours	Pune Distribution Center -> Bangalore Tech Hub (Direct Express)	1	MEDIUM	ACTIVE	1	5
282	1011	18 Hours	Pune Distribution Center -> Kolhapur -> Bangalore Tech Hub (Primary)	2	HIGH	ACTIVE	1	5
283	1015	18 Hours	Pune Distribution Center -> Solapur -> Mangalore -> Bangalore Tech Hub	3	LOW	ACTIVE	1	5
284	1038	19 Hours	Pune Distribution Center -> Hubli -> Kolhapur -> Bangalore Tech Hub	4	MEDIUM	ACTIVE	1	5
285	1061	19 Hours	Pune Distribution Center -> Belgaum -> Solapur -> Bangalore Tech Hub	5	HIGH	ACTIVE	1	5
286	1088	20 Hours	Pune Distribution Center -> Kolhapur -> Mangalore -> Bangalore Tech Hub	6	LOW	ACTIVE	1	5
287	1086	20 Hours	Pune Distribution Center -> Solapur -> Hyderabad -> Bangalore Tech Hub	7	MEDIUM	ACTIVE	1	5
288	1096	20 Hours	Pune Distribution Center -> Hubli -> Solapur -> Bangalore Tech Hub	8	HIGH	ACTIVE	1	5
289	1107	20 Hours	Pune Distribution Center -> Belgaum -> Mangalore -> Bangalore Tech Hub	9	LOW	ACTIVE	1	5
290	1119	20 Hours	Pune Distribution Center -> Kolhapur -> Hyderabad -> Bangalore Tech Hub	10	MEDIUM	ACTIVE	1	5
291	796	15 Hours	Pune Distribution Center -> Hyderabad Logistics Hub (Direct Express)	1	MEDIUM	ACTIVE	2	5
292	828	15 Hours	Pune Distribution Center -> Aurangabad -> Hyderabad Logistics Hub (Primary)	2	HIGH	ACTIVE	2	5
293	832	15 Hours	Pune Distribution Center -> Kolhapur -> Belgaum -> Hyderabad Logistics Hub	3	LOW	ACTIVE	2	5
294	840	16 Hours	Pune Distribution Center -> Solapur -> Aurangabad -> Hyderabad Logistics Hub	4	MEDIUM	ACTIVE	2	5
295	855	16 Hours	Pune Distribution Center -> Nizamabad -> Kolhapur -> Hyderabad Logistics Hub	5	HIGH	ACTIVE	2	5
296	844	16 Hours	Pune Distribution Center -> Aurangabad -> Belgaum -> Hyderabad Logistics Hub	6	LOW	ACTIVE	2	5
297	867	16 Hours	Pune Distribution Center -> Kolhapur -> Hubli -> Hyderabad Logistics Hub	7	MEDIUM	ACTIVE	2	5
298	912	17 Hours	Pune Distribution Center -> Solapur -> Kolhapur -> Hyderabad Logistics Hub	8	HIGH	ACTIVE	2	5
299	914	17 Hours	Pune Distribution Center -> Nizamabad -> Belgaum -> Hyderabad Logistics Hub	9	LOW	ACTIVE	2	5
300	912	17 Hours	Pune Distribution Center -> Aurangabad -> Hubli -> Hyderabad Logistics Hub	10	MEDIUM	ACTIVE	2	5
301	607	12 Hours	Pune Distribution Center -> Chennai Port Warehouse (Direct Express)	1	MEDIUM	ACTIVE	3	5
302	606	12 Hours	Pune Distribution Center -> Solapur -> Chennai Port Warehouse (Primary)	2	HIGH	ACTIVE	3	5
303	615	12 Hours	Pune Distribution Center -> Belgaum -> Bangalore -> Chennai Port Warehouse	3	LOW	ACTIVE	3	5
304	632	12 Hours	Pune Distribution Center -> Hubli -> Solapur -> Chennai Port Warehouse	4	MEDIUM	ACTIVE	3	5
305	652	12 Hours	Pune Distribution Center -> Hyderabad -> Belgaum -> Chennai Port Warehouse	5	HIGH	ACTIVE	3	5
306	644	12 Hours	Pune Distribution Center -> Solapur -> Bangalore -> Chennai Port Warehouse	6	LOW	ACTIVE	3	5
307	670	13 Hours	Pune Distribution Center -> Belgaum -> Kolhapur -> Chennai Port Warehouse	7	MEDIUM	ACTIVE	3	5
308	671	13 Hours	Pune Distribution Center -> Hubli -> Belgaum -> Chennai Port Warehouse	8	HIGH	ACTIVE	3	5
309	732	14 Hours	Pune Distribution Center -> Hyderabad -> Bangalore -> Chennai Port Warehouse	9	LOW	ACTIVE	3	5
310	737	14 Hours	Pune Distribution Center -> Solapur -> Kolhapur -> Chennai Port Warehouse	10	MEDIUM	ACTIVE	3	5
311	399	8 Hours	Pune Distribution Center -> Kolkata East Hub (Direct Express)	1	MEDIUM	ACTIVE	4	5
312	396	8 Hours	Pune Distribution Center -> Warangal -> Kolkata East Hub (Primary)	2	HIGH	ACTIVE	4	5
313	430	9 Hours	Pune Distribution Center -> Amravati -> Nizamabad -> Kolkata East Hub	3	LOW	ACTIVE	4	5
314	423	9 Hours	Pune Distribution Center -> Nagpur -> Warangal -> Kolkata East Hub	4	MEDIUM	ACTIVE	4	5
315	441	9 Hours	Pune Distribution Center -> Jabalpur -> Amravati -> Kolkata East Hub	5	HIGH	ACTIVE	4	5
316	456	9 Hours	Pune Distribution Center -> Warangal -> Nizamabad -> Kolkata East Hub	6	LOW	ACTIVE	4	5
317	488	10 Hours	Pune Distribution Center -> Amravati -> Hyderabad -> Kolkata East Hub	7	MEDIUM	ACTIVE	4	5
318	474	9 Hours	Pune Distribution Center -> Nagpur -> Amravati -> Kolkata East Hub	8	HIGH	ACTIVE	4	5
319	521	10 Hours	Pune Distribution Center -> Jabalpur -> Nizamabad -> Kolkata East Hub	9	LOW	ACTIVE	4	5
320	531	10 Hours	Pune Distribution Center -> Warangal -> Hyderabad -> Kolkata East Hub	10	MEDIUM	ACTIVE	4	5
321	376	8 Hours	Pune Distribution Center -> Ahmedabad Trade Hub (Direct Express)	1	MEDIUM	ACTIVE	6	5
322	417	8 Hours	Pune Distribution Center -> Bhavnagar -> Ahmedabad Trade Hub (Primary)	2	HIGH	ACTIVE	6	5
323	442	9 Hours	Pune Distribution Center -> Vadodara -> Thane -> Ahmedabad Trade Hub	3	LOW	ACTIVE	6	5
324	411	8 Hours	Pune Distribution Center -> Surat -> Bhavnagar -> Ahmedabad Trade Hub	4	MEDIUM	ACTIVE	6	5
325	430	9 Hours	Pune Distribution Center -> Nasik -> Vadodara -> Ahmedabad Trade Hub	5	HIGH	ACTIVE	6	5
326	445	9 Hours	Pune Distribution Center -> Bhavnagar -> Thane -> Ahmedabad Trade Hub	6	LOW	ACTIVE	6	5
327	465	9 Hours	Pune Distribution Center -> Vadodara -> Mumbai -> Ahmedabad Trade Hub	7	MEDIUM	ACTIVE	6	5
328	487	10 Hours	Pune Distribution Center -> Surat -> Vadodara -> Ahmedabad Trade Hub	8	HIGH	ACTIVE	6	5
329	501	10 Hours	Pune Distribution Center -> Nasik -> Thane -> Ahmedabad Trade Hub	9	LOW	ACTIVE	6	5
330	527	10 Hours	Pune Distribution Center -> Bhavnagar -> Mumbai -> Ahmedabad Trade Hub	10	MEDIUM	ACTIVE	6	5
331	571	11 Hours	Pune Distribution Center -> Jaipur Regional Hub (Direct Express)	1	MEDIUM	ACTIVE	7	5
332	588	11 Hours	Pune Distribution Center -> Udaipur -> Jaipur Regional Hub (Primary)	2	HIGH	ACTIVE	7	5
333	605	12 Hours	Pune Distribution Center -> Ahmedabad -> Surat -> Jaipur Regional Hub	3	LOW	ACTIVE	7	5
334	649	12 Hours	Pune Distribution Center -> Indore -> Udaipur -> Jaipur Regional Hub	4	MEDIUM	ACTIVE	7	5
335	643	12 Hours	Pune Distribution Center -> Vadodara -> Ahmedabad -> Jaipur Regional Hub	5	HIGH	ACTIVE	7	5
336	660	13 Hours	Pune Distribution Center -> Udaipur -> Surat -> Jaipur Regional Hub	6	LOW	ACTIVE	7	5
337	675	13 Hours	Pune Distribution Center -> Ahmedabad -> Bhopal -> Jaipur Regional Hub	7	MEDIUM	ACTIVE	7	5
338	694	13 Hours	Pune Distribution Center -> Indore -> Ahmedabad -> Jaipur Regional Hub	8	HIGH	ACTIVE	7	5
339	711	13 Hours	Pune Distribution Center -> Vadodara -> Surat -> Jaipur Regional Hub	9	LOW	ACTIVE	7	5
340	707	13 Hours	Pune Distribution Center -> Udaipur -> Bhopal -> Jaipur Regional Hub	10	MEDIUM	ACTIVE	7	5
341	804	15 Hours	Pune Distribution Center -> Lucknow Supply Center (Direct Express)	1	MEDIUM	ACTIVE	8	5
342	812	15 Hours	Pune Distribution Center -> Amravati -> Lucknow Supply Center (Primary)	2	HIGH	ACTIVE	8	5
343	801	15 Hours	Pune Distribution Center -> Nagpur -> Jabalpur -> Lucknow Supply Center	3	LOW	ACTIVE	8	5
344	852	16 Hours	Pune Distribution Center -> Bhopal -> Amravati -> Lucknow Supply Center	4	MEDIUM	ACTIVE	8	5
345	869	16 Hours	Pune Distribution Center -> Indore -> Nagpur -> Lucknow Supply Center	5	HIGH	ACTIVE	8	5
346	870	16 Hours	Pune Distribution Center -> Amravati -> Jabalpur -> Lucknow Supply Center	6	LOW	ACTIVE	8	5
347	859	16 Hours	Pune Distribution Center -> Nagpur -> Aurangabad -> Lucknow Supply Center	7	MEDIUM	ACTIVE	8	5
348	903	17 Hours	Pune Distribution Center -> Bhopal -> Nagpur -> Lucknow Supply Center	8	HIGH	ACTIVE	8	5
349	890	16 Hours	Pune Distribution Center -> Indore -> Jabalpur -> Lucknow Supply Center	9	LOW	ACTIVE	8	5
350	915	17 Hours	Pune Distribution Center -> Amravati -> Aurangabad -> Lucknow Supply Center	10	MEDIUM	ACTIVE	8	5
351	1206	22 Hours	Ahmedabad Trade Hub -> Bangalore Tech Hub (Direct Express)	1	MEDIUM	ACTIVE	1	6
352	1182	21 Hours	Ahmedabad Trade Hub -> Kolhapur -> Bangalore Tech Hub (Primary)	2	HIGH	ACTIVE	1	6
353	1243	22 Hours	Ahmedabad Trade Hub -> Lonavala -> Aurangabad -> Bangalore Tech Hub	3	LOW	ACTIVE	1	6
354	1215	22 Hours	Ahmedabad Trade Hub -> Solapur -> Kolhapur -> Bangalore Tech Hub	4	MEDIUM	ACTIVE	1	6
355	1247	22 Hours	Ahmedabad Trade Hub -> Pune -> Lonavala -> Bangalore Tech Hub	5	HIGH	ACTIVE	1	6
356	1243	22 Hours	Ahmedabad Trade Hub -> Kolhapur -> Aurangabad -> Bangalore Tech Hub	6	LOW	ACTIVE	1	6
357	1263	23 Hours	Ahmedabad Trade Hub -> Lonavala -> Belgaum -> Bangalore Tech Hub	7	MEDIUM	ACTIVE	1	6
358	1310	23 Hours	Ahmedabad Trade Hub -> Solapur -> Lonavala -> Bangalore Tech Hub	8	HIGH	ACTIVE	1	6
359	1310	23 Hours	Ahmedabad Trade Hub -> Pune -> Aurangabad -> Bangalore Tech Hub	9	LOW	ACTIVE	1	6
360	1325	24 Hours	Ahmedabad Trade Hub -> Kolhapur -> Belgaum -> Bangalore Tech Hub	10	MEDIUM	ACTIVE	1	6
361	988	18 Hours	Ahmedabad Trade Hub -> Hyderabad Logistics Hub (Direct Express)	1	MEDIUM	ACTIVE	2	6
362	1002	18 Hours	Ahmedabad Trade Hub -> Amravati -> Hyderabad Logistics Hub (Primary)	2	HIGH	ACTIVE	2	6
363	1028	19 Hours	Ahmedabad Trade Hub -> Pune -> Indore -> Hyderabad Logistics Hub	3	LOW	ACTIVE	2	6
364	1050	19 Hours	Ahmedabad Trade Hub -> Aurangabad -> Amravati -> Hyderabad Logistics Hub	4	MEDIUM	ACTIVE	2	6
365	1034	19 Hours	Ahmedabad Trade Hub -> Nasik -> Pune -> Hyderabad Logistics Hub	5	HIGH	ACTIVE	2	6
366	1085	20 Hours	Ahmedabad Trade Hub -> Amravati -> Indore -> Hyderabad Logistics Hub	6	LOW	ACTIVE	2	6
367	1087	20 Hours	Ahmedabad Trade Hub -> Pune -> Lonavala -> Hyderabad Logistics Hub	7	MEDIUM	ACTIVE	2	6
368	1090	20 Hours	Ahmedabad Trade Hub -> Aurangabad -> Pune -> Hyderabad Logistics Hub	8	HIGH	ACTIVE	2	6
369	1096	20 Hours	Ahmedabad Trade Hub -> Nasik -> Indore -> Hyderabad Logistics Hub	9	LOW	ACTIVE	2	6
370	1107	20 Hours	Ahmedabad Trade Hub -> Amravati -> Lonavala -> Hyderabad Logistics Hub	10	MEDIUM	ACTIVE	2	6
371	795	15 Hours	Ahmedabad Trade Hub -> Chennai Port Warehouse (Direct Express)	1	MEDIUM	ACTIVE	3	6
372	822	15 Hours	Ahmedabad Trade Hub -> Aurangabad -> Chennai Port Warehouse (Primary)	2	HIGH	ACTIVE	3	6
373	817	15 Hours	Ahmedabad Trade Hub -> Hyderabad -> Kolhapur -> Chennai Port Warehouse	3	LOW	ACTIVE	3	6
374	819	15 Hours	Ahmedabad Trade Hub -> Solapur -> Aurangabad -> Chennai Port Warehouse	4	MEDIUM	ACTIVE	3	6
375	867	16 Hours	Ahmedabad Trade Hub -> Nizamabad -> Hyderabad -> Chennai Port Warehouse	5	HIGH	ACTIVE	3	6
376	852	16 Hours	Ahmedabad Trade Hub -> Aurangabad -> Kolhapur -> Chennai Port Warehouse	6	LOW	ACTIVE	3	6
377	876	16 Hours	Ahmedabad Trade Hub -> Hyderabad -> Pune -> Chennai Port Warehouse	7	MEDIUM	ACTIVE	3	6
378	889	16 Hours	Ahmedabad Trade Hub -> Solapur -> Hyderabad -> Chennai Port Warehouse	8	HIGH	ACTIVE	3	6
379	885	16 Hours	Ahmedabad Trade Hub -> Nizamabad -> Kolhapur -> Chennai Port Warehouse	9	LOW	ACTIVE	3	6
380	942	17 Hours	Ahmedabad Trade Hub -> Aurangabad -> Pune -> Chennai Port Warehouse	10	MEDIUM	ACTIVE	3	6
381	573	11 Hours	Ahmedabad Trade Hub -> Kolkata East Hub (Direct Express)	1	MEDIUM	ACTIVE	4	6
382	591	11 Hours	Ahmedabad Trade Hub -> Prayagraj -> Kolkata East Hub (Primary)	2	HIGH	ACTIVE	4	6
383	632	12 Hours	Ahmedabad Trade Hub -> Bhopal -> Amravati -> Kolkata East Hub	3	LOW	ACTIVE	4	6
384	629	12 Hours	Ahmedabad Trade Hub -> Jabalpur -> Prayagraj -> Kolkata East Hub	4	MEDIUM	ACTIVE	4	6
385	666	13 Hours	Ahmedabad Trade Hub -> Nagpur -> Bhopal -> Kolkata East Hub	5	HIGH	ACTIVE	4	6
386	669	13 Hours	Ahmedabad Trade Hub -> Prayagraj -> Amravati -> Kolkata East Hub	6	LOW	ACTIVE	4	6
387	670	13 Hours	Ahmedabad Trade Hub -> Bhopal -> Varanasi -> Kolkata East Hub	7	MEDIUM	ACTIVE	4	6
388	685	13 Hours	Ahmedabad Trade Hub -> Jabalpur -> Bhopal -> Kolkata East Hub	8	HIGH	ACTIVE	4	6
389	734	14 Hours	Ahmedabad Trade Hub -> Nagpur -> Amravati -> Kolkata East Hub	9	LOW	ACTIVE	4	6
390	714	13 Hours	Ahmedabad Trade Hub -> Prayagraj -> Varanasi -> Kolkata East Hub	10	MEDIUM	ACTIVE	4	6
391	406	8 Hours	Ahmedabad Trade Hub -> Pune Distribution Center (Direct Express)	1	MEDIUM	ACTIVE	5	6
392	402	8 Hours	Ahmedabad Trade Hub -> Bhavnagar -> Pune Distribution Center (Primary)	2	HIGH	ACTIVE	5	6
393	422	9 Hours	Ahmedabad Trade Hub -> Vadodara -> Thane -> Pune Distribution Center	3	LOW	ACTIVE	5	6
394	431	9 Hours	Ahmedabad Trade Hub -> Surat -> Bhavnagar -> Pune Distribution Center	4	MEDIUM	ACTIVE	5	6
395	449	9 Hours	Ahmedabad Trade Hub -> Nasik -> Vadodara -> Pune Distribution Center	5	HIGH	ACTIVE	5	6
396	474	9 Hours	Ahmedabad Trade Hub -> Bhavnagar -> Thane -> Pune Distribution Center	6	LOW	ACTIVE	5	6
397	489	10 Hours	Ahmedabad Trade Hub -> Vadodara -> Mumbai -> Pune Distribution Center	7	MEDIUM	ACTIVE	5	6
398	487	10 Hours	Ahmedabad Trade Hub -> Surat -> Vadodara -> Pune Distribution Center	8	HIGH	ACTIVE	5	6
399	517	10 Hours	Ahmedabad Trade Hub -> Nasik -> Thane -> Pune Distribution Center	9	LOW	ACTIVE	5	6
400	528	10 Hours	Ahmedabad Trade Hub -> Bhavnagar -> Mumbai -> Pune Distribution Center	10	MEDIUM	ACTIVE	5	6
401	388	8 Hours	Ahmedabad Trade Hub -> Jaipur Regional Hub (Direct Express)	1	MEDIUM	ACTIVE	7	6
402	405	8 Hours	Ahmedabad Trade Hub -> Jodhpur -> Jaipur Regional Hub (Primary)	2	HIGH	ACTIVE	7	6
403	400	8 Hours	Ahmedabad Trade Hub -> Indore -> Vadodara -> Jaipur Regional Hub	3	LOW	ACTIVE	7	6
404	436	9 Hours	Ahmedabad Trade Hub -> Udaipur -> Jodhpur -> Jaipur Regional Hub	4	MEDIUM	ACTIVE	7	6
405	434	9 Hours	Ahmedabad Trade Hub -> Ajmer -> Indore -> Jaipur Regional Hub	5	HIGH	ACTIVE	7	6
406	450	9 Hours	Ahmedabad Trade Hub -> Jodhpur -> Vadodara -> Jaipur Regional Hub	6	LOW	ACTIVE	7	6
407	485	10 Hours	Ahmedabad Trade Hub -> Indore -> Bikaner -> Jaipur Regional Hub	7	MEDIUM	ACTIVE	7	6
408	470	9 Hours	Ahmedabad Trade Hub -> Udaipur -> Indore -> Jaipur Regional Hub	8	HIGH	ACTIVE	7	6
409	489	10 Hours	Ahmedabad Trade Hub -> Ajmer -> Vadodara -> Jaipur Regional Hub	9	LOW	ACTIVE	7	6
410	522	10 Hours	Ahmedabad Trade Hub -> Jodhpur -> Bikaner -> Jaipur Regional Hub	10	MEDIUM	ACTIVE	7	6
411	569	11 Hours	Ahmedabad Trade Hub -> Lucknow Supply Center (Direct Express)	1	MEDIUM	ACTIVE	8	6
412	613	12 Hours	Ahmedabad Trade Hub -> Jaipur -> Lucknow Supply Center (Primary)	2	HIGH	ACTIVE	8	6
413	605	12 Hours	Ahmedabad Trade Hub -> Indore -> Agra -> Lucknow Supply Center	3	LOW	ACTIVE	8	6
414	632	12 Hours	Ahmedabad Trade Hub -> Bhopal -> Jaipur -> Lucknow Supply Center	4	MEDIUM	ACTIVE	8	6
415	649	12 Hours	Ahmedabad Trade Hub -> Gwalior -> Indore -> Lucknow Supply Center	5	HIGH	ACTIVE	8	6
416	686	13 Hours	Ahmedabad Trade Hub -> Jaipur -> Agra -> Lucknow Supply Center	6	LOW	ACTIVE	8	6
417	661	13 Hours	Ahmedabad Trade Hub -> Indore -> Ajmer -> Lucknow Supply Center	7	MEDIUM	ACTIVE	8	6
418	675	13 Hours	Ahmedabad Trade Hub -> Bhopal -> Indore -> Lucknow Supply Center	8	HIGH	ACTIVE	8	6
419	707	13 Hours	Ahmedabad Trade Hub -> Gwalior -> Agra -> Lucknow Supply Center	9	LOW	ACTIVE	8	6
420	734	14 Hours	Ahmedabad Trade Hub -> Jaipur -> Ajmer -> Lucknow Supply Center	10	MEDIUM	ACTIVE	8	6
421	1384	25 Hours	Jaipur Regional Hub -> Bangalore Tech Hub (Direct Express)	1	MEDIUM	ACTIVE	1	7
422	1382	25 Hours	Jaipur Regional Hub -> Nizamabad -> Bangalore Tech Hub (Primary)	2	HIGH	ACTIVE	1	7
423	1416	25 Hours	Jaipur Regional Hub -> Solapur -> Nagpur -> Bangalore Tech Hub	3	LOW	ACTIVE	1	7
424	1432	25 Hours	Jaipur Regional Hub -> Aurangabad -> Nizamabad -> Bangalore Tech Hub	4	MEDIUM	ACTIVE	1	7
425	1429	25 Hours	Jaipur Regional Hub -> Amravati -> Solapur -> Bangalore Tech Hub	5	HIGH	ACTIVE	1	7
426	1447	26 Hours	Jaipur Regional Hub -> Nizamabad -> Nagpur -> Bangalore Tech Hub	6	LOW	ACTIVE	1	7
427	1456	26 Hours	Jaipur Regional Hub -> Solapur -> Indore -> Bangalore Tech Hub	7	MEDIUM	ACTIVE	1	7
428	1478	26 Hours	Jaipur Regional Hub -> Aurangabad -> Solapur -> Bangalore Tech Hub	8	HIGH	ACTIVE	1	7
429	1532	27 Hours	Jaipur Regional Hub -> Amravati -> Nagpur -> Bangalore Tech Hub	9	LOW	ACTIVE	1	7
430	1533	27 Hours	Jaipur Regional Hub -> Nizamabad -> Indore -> Bangalore Tech Hub	10	MEDIUM	ACTIVE	1	7
431	1192	21 Hours	Jaipur Regional Hub -> Hyderabad Logistics Hub (Direct Express)	1	MEDIUM	ACTIVE	2	7
432	1227	22 Hours	Jaipur Regional Hub -> Indore -> Hyderabad Logistics Hub (Primary)	2	HIGH	ACTIVE	2	7
433	1223	22 Hours	Jaipur Regional Hub -> Nagpur -> Aurangabad -> Hyderabad Logistics Hub	3	LOW	ACTIVE	2	7
434	1215	22 Hours	Jaipur Regional Hub -> Bhopal -> Indore -> Hyderabad Logistics Hub	4	MEDIUM	ACTIVE	2	7
435	1248	22 Hours	Jaipur Regional Hub -> Amravati -> Nagpur -> Hyderabad Logistics Hub	5	HIGH	ACTIVE	2	7
436	1242	22 Hours	Jaipur Regional Hub -> Indore -> Aurangabad -> Hyderabad Logistics Hub	6	LOW	ACTIVE	2	7
437	1278	23 Hours	Jaipur Regional Hub -> Nagpur -> Jabalpur -> Hyderabad Logistics Hub	7	MEDIUM	ACTIVE	2	7
438	1289	23 Hours	Jaipur Regional Hub -> Bhopal -> Nagpur -> Hyderabad Logistics Hub	8	HIGH	ACTIVE	2	7
439	1302	23 Hours	Jaipur Regional Hub -> Amravati -> Aurangabad -> Hyderabad Logistics Hub	9	LOW	ACTIVE	2	7
440	1329	24 Hours	Jaipur Regional Hub -> Indore -> Jabalpur -> Hyderabad Logistics Hub	10	MEDIUM	ACTIVE	2	7
441	1001	18 Hours	Jaipur Regional Hub -> Chennai Port Warehouse (Direct Express)	1	MEDIUM	ACTIVE	3	7
442	1009	18 Hours	Jaipur Regional Hub -> Nagpur -> Chennai Port Warehouse (Primary)	2	HIGH	ACTIVE	3	7
443	999	18 Hours	Jaipur Regional Hub -> Warangal -> Hyderabad -> Chennai Port Warehouse	3	LOW	ACTIVE	3	7
444	1023	19 Hours	Jaipur Regional Hub -> Amravati -> Nagpur -> Chennai Port Warehouse	4	MEDIUM	ACTIVE	3	7
445	1038	19 Hours	Jaipur Regional Hub -> Nizamabad -> Warangal -> Chennai Port Warehouse	5	HIGH	ACTIVE	3	7
446	1071	19 Hours	Jaipur Regional Hub -> Nagpur -> Hyderabad -> Chennai Port Warehouse	6	LOW	ACTIVE	3	7
447	1091	20 Hours	Jaipur Regional Hub -> Warangal -> Aurangabad -> Chennai Port Warehouse	7	MEDIUM	ACTIVE	3	7
448	1086	20 Hours	Jaipur Regional Hub -> Amravati -> Warangal -> Chennai Port Warehouse	8	HIGH	ACTIVE	3	7
449	1110	20 Hours	Jaipur Regional Hub -> Nizamabad -> Hyderabad -> Chennai Port Warehouse	9	LOW	ACTIVE	3	7
450	1104	20 Hours	Jaipur Regional Hub -> Nagpur -> Aurangabad -> Chennai Port Warehouse	10	MEDIUM	ACTIVE	3	7
451	813	15 Hours	Jaipur Regional Hub -> Kolkata East Hub (Direct Express)	1	MEDIUM	ACTIVE	4	7
452	829	15 Hours	Jaipur Regional Hub -> Lucknow -> Kolkata East Hub (Primary)	2	HIGH	ACTIVE	4	7
453	826	15 Hours	Jaipur Regional Hub -> Kanpur -> Jabalpur -> Kolkata East Hub	3	LOW	ACTIVE	4	7
454	849	16 Hours	Jaipur Regional Hub -> Prayagraj -> Lucknow -> Kolkata East Hub	4	MEDIUM	ACTIVE	4	7
455	834	15 Hours	Jaipur Regional Hub -> Varanasi -> Kanpur -> Kolkata East Hub	5	HIGH	ACTIVE	4	7
456	848	16 Hours	Jaipur Regional Hub -> Lucknow -> Jabalpur -> Kolkata East Hub	6	LOW	ACTIVE	4	7
457	899	16 Hours	Jaipur Regional Hub -> Kanpur -> Gaya -> Kolkata East Hub	7	MEDIUM	ACTIVE	4	7
458	904	17 Hours	Jaipur Regional Hub -> Prayagraj -> Kanpur -> Kolkata East Hub	8	HIGH	ACTIVE	4	7
459	924	17 Hours	Jaipur Regional Hub -> Varanasi -> Jabalpur -> Kolkata East Hub	9	LOW	ACTIVE	4	7
460	909	17 Hours	Jaipur Regional Hub -> Lucknow -> Gaya -> Kolkata East Hub	10	MEDIUM	ACTIVE	4	7
461	595	11 Hours	Jaipur Regional Hub -> Pune Distribution Center (Direct Express)	1	MEDIUM	ACTIVE	5	7
462	611	12 Hours	Jaipur Regional Hub -> Udaipur -> Pune Distribution Center (Primary)	2	HIGH	ACTIVE	5	7
463	598	11 Hours	Jaipur Regional Hub -> Ahmedabad -> Surat -> Pune Distribution Center	3	LOW	ACTIVE	5	7
464	644	12 Hours	Jaipur Regional Hub -> Indore -> Udaipur -> Pune Distribution Center	4	MEDIUM	ACTIVE	5	7
465	632	12 Hours	Jaipur Regional Hub -> Vadodara -> Ahmedabad -> Pune Distribution Center	5	HIGH	ACTIVE	5	7
466	672	13 Hours	Jaipur Regional Hub -> Udaipur -> Surat -> Pune Distribution Center	6	LOW	ACTIVE	5	7
467	673	13 Hours	Jaipur Regional Hub -> Ahmedabad -> Bhopal -> Pune Distribution Center	7	MEDIUM	ACTIVE	5	7
468	676	13 Hours	Jaipur Regional Hub -> Indore -> Ahmedabad -> Pune Distribution Center	8	HIGH	ACTIVE	5	7
469	699	13 Hours	Jaipur Regional Hub -> Vadodara -> Surat -> Pune Distribution Center	9	LOW	ACTIVE	5	7
470	724	14 Hours	Jaipur Regional Hub -> Udaipur -> Bhopal -> Pune Distribution Center	10	MEDIUM	ACTIVE	5	7
471	384	8 Hours	Jaipur Regional Hub -> Ahmedabad Trade Hub (Direct Express)	1	MEDIUM	ACTIVE	6	7
472	417	8 Hours	Jaipur Regional Hub -> Jodhpur -> Ahmedabad Trade Hub (Primary)	2	HIGH	ACTIVE	6	7
473	403	8 Hours	Jaipur Regional Hub -> Indore -> Vadodara -> Ahmedabad Trade Hub	3	LOW	ACTIVE	6	7
474	444	9 Hours	Jaipur Regional Hub -> Udaipur -> Jodhpur -> Ahmedabad Trade Hub	4	MEDIUM	ACTIVE	6	7
475	433	9 Hours	Jaipur Regional Hub -> Ajmer -> Indore -> Ahmedabad Trade Hub	5	HIGH	ACTIVE	6	7
476	474	9 Hours	Jaipur Regional Hub -> Jodhpur -> Vadodara -> Ahmedabad Trade Hub	6	LOW	ACTIVE	6	7
477	476	9 Hours	Jaipur Regional Hub -> Indore -> Bikaner -> Ahmedabad Trade Hub	7	MEDIUM	ACTIVE	6	7
478	507	10 Hours	Jaipur Regional Hub -> Udaipur -> Indore -> Ahmedabad Trade Hub	8	HIGH	ACTIVE	6	7
479	507	10 Hours	Jaipur Regional Hub -> Ajmer -> Vadodara -> Ahmedabad Trade Hub	9	LOW	ACTIVE	6	7
480	522	10 Hours	Jaipur Regional Hub -> Jodhpur -> Bikaner -> Ahmedabad Trade Hub	10	MEDIUM	ACTIVE	6	7
481	384	8 Hours	Jaipur Regional Hub -> Lucknow Supply Center (Direct Express)	1	MEDIUM	ACTIVE	8	7
482	403	8 Hours	Jaipur Regional Hub -> Ghaziabad -> Lucknow Supply Center (Primary)	2	HIGH	ACTIVE	8	7
483	405	8 Hours	Jaipur Regional Hub -> Kanpur -> Bhopal -> Lucknow Supply Center	3	LOW	ACTIVE	8	7
484	437	9 Hours	Jaipur Regional Hub -> Agra -> Ghaziabad -> Lucknow Supply Center	4	MEDIUM	ACTIVE	8	7
485	442	9 Hours	Jaipur Regional Hub -> Gwalior -> Kanpur -> Lucknow Supply Center	5	HIGH	ACTIVE	8	7
486	482	10 Hours	Jaipur Regional Hub -> Ghaziabad -> Bhopal -> Lucknow Supply Center	6	LOW	ACTIVE	8	7
487	478	9 Hours	Jaipur Regional Hub -> Kanpur -> Ajmer -> Lucknow Supply Center	7	MEDIUM	ACTIVE	8	7
488	480	10 Hours	Jaipur Regional Hub -> Agra -> Kanpur -> Lucknow Supply Center	8	HIGH	ACTIVE	8	7
489	496	10 Hours	Jaipur Regional Hub -> Gwalior -> Bhopal -> Lucknow Supply Center	9	LOW	ACTIVE	8	7
490	540	11 Hours	Jaipur Regional Hub -> Ghaziabad -> Ajmer -> Lucknow Supply Center	10	MEDIUM	ACTIVE	8	7
491	1587	28 Hours	Lucknow Supply Center -> Bangalore Tech Hub (Direct Express)	1	MEDIUM	ACTIVE	1	8
492	1627	29 Hours	Lucknow Supply Center -> Amravati -> Bangalore Tech Hub (Primary)	2	HIGH	ACTIVE	1	8
493	1620	29 Hours	Lucknow Supply Center -> Warangal -> Hyderabad -> Bangalore Tech Hub	3	LOW	ACTIVE	1	8
494	1612	28 Hours	Lucknow Supply Center -> Nagpur -> Amravati -> Bangalore Tech Hub	4	MEDIUM	ACTIVE	1	8
495	1654	29 Hours	Lucknow Supply Center -> Nizamabad -> Warangal -> Bangalore Tech Hub	5	HIGH	ACTIVE	1	8
496	1689	30 Hours	Lucknow Supply Center -> Amravati -> Hyderabad -> Bangalore Tech Hub	6	LOW	ACTIVE	1	8
497	1664	29 Hours	Lucknow Supply Center -> Warangal -> Jabalpur -> Bangalore Tech Hub	7	MEDIUM	ACTIVE	1	8
498	1696	30 Hours	Lucknow Supply Center -> Nagpur -> Warangal -> Bangalore Tech Hub	8	HIGH	ACTIVE	1	8
499	1709	30 Hours	Lucknow Supply Center -> Nizamabad -> Hyderabad -> Bangalore Tech Hub	9	LOW	ACTIVE	1	8
500	1713	30 Hours	Lucknow Supply Center -> Amravati -> Jabalpur -> Bangalore Tech Hub	10	MEDIUM	ACTIVE	1	8
501	1375	24 Hours	Lucknow Supply Center -> Hyderabad Logistics Hub (Direct Express)	1	MEDIUM	ACTIVE	2	8
502	1429	25 Hours	Lucknow Supply Center -> Amravati -> Hyderabad Logistics Hub (Primary)	2	HIGH	ACTIVE	2	8
503	1409	25 Hours	Lucknow Supply Center -> Bhopal -> Nizamabad -> Hyderabad Logistics Hub	3	LOW	ACTIVE	2	8
504	1428	25 Hours	Lucknow Supply Center -> Jabalpur -> Amravati -> Hyderabad Logistics Hub	4	MEDIUM	ACTIVE	2	8
505	1433	25 Hours	Lucknow Supply Center -> Nagpur -> Bhopal -> Hyderabad Logistics Hub	5	HIGH	ACTIVE	2	8
506	1442	26 Hours	Lucknow Supply Center -> Amravati -> Nizamabad -> Hyderabad Logistics Hub	6	LOW	ACTIVE	2	8
507	1487	26 Hours	Lucknow Supply Center -> Bhopal -> Indore -> Hyderabad Logistics Hub	7	MEDIUM	ACTIVE	2	8
508	1518	27 Hours	Lucknow Supply Center -> Jabalpur -> Bhopal -> Hyderabad Logistics Hub	8	HIGH	ACTIVE	2	8
509	1513	27 Hours	Lucknow Supply Center -> Nagpur -> Nizamabad -> Hyderabad Logistics Hub	9	LOW	ACTIVE	2	8
510	1539	27 Hours	Lucknow Supply Center -> Amravati -> Indore -> Hyderabad Logistics Hub	10	MEDIUM	ACTIVE	2	8
511	1186	21 Hours	Lucknow Supply Center -> Chennai Port Warehouse (Direct Express)	1	MEDIUM	ACTIVE	3	8
512	1216	22 Hours	Lucknow Supply Center -> Nizamabad -> Chennai Port Warehouse (Primary)	2	HIGH	ACTIVE	3	8
513	1244	22 Hours	Lucknow Supply Center -> Amravati -> Jabalpur -> Chennai Port Warehouse	3	LOW	ACTIVE	3	8
514	1217	22 Hours	Lucknow Supply Center -> Nagpur -> Nizamabad -> Chennai Port Warehouse	4	MEDIUM	ACTIVE	3	8
515	1234	22 Hours	Lucknow Supply Center -> Warangal -> Amravati -> Chennai Port Warehouse	5	HIGH	ACTIVE	3	8
516	1267	23 Hours	Lucknow Supply Center -> Nizamabad -> Jabalpur -> Chennai Port Warehouse	6	LOW	ACTIVE	3	8
517	1255	22 Hours	Lucknow Supply Center -> Amravati -> Hyderabad -> Chennai Port Warehouse	7	MEDIUM	ACTIVE	3	8
518	1283	23 Hours	Lucknow Supply Center -> Nagpur -> Amravati -> Chennai Port Warehouse	8	HIGH	ACTIVE	3	8
519	1304	23 Hours	Lucknow Supply Center -> Warangal -> Jabalpur -> Chennai Port Warehouse	9	LOW	ACTIVE	3	8
520	1319	23 Hours	Lucknow Supply Center -> Nizamabad -> Hyderabad -> Chennai Port Warehouse	10	MEDIUM	ACTIVE	3	8
521	982	18 Hours	Lucknow Supply Center -> Kolkata East Hub (Direct Express)	1	MEDIUM	ACTIVE	4	8
522	996	18 Hours	Lucknow Supply Center -> Varanasi -> Kolkata East Hub (Primary)	2	HIGH	ACTIVE	4	8
523	1032	19 Hours	Lucknow Supply Center -> Asansol -> Prayagraj -> Kolkata East Hub	3	LOW	ACTIVE	4	8
524	1020	19 Hours	Lucknow Supply Center -> Gaya -> Varanasi -> Kolkata East Hub	4	MEDIUM	ACTIVE	4	8
525	1067	19 Hours	Lucknow Supply Center -> Patna -> Asansol -> Kolkata East Hub	5	HIGH	ACTIVE	4	8
526	1087	20 Hours	Lucknow Supply Center -> Varanasi -> Prayagraj -> Kolkata East Hub	6	LOW	ACTIVE	4	8
527	1084	20 Hours	Lucknow Supply Center -> Asansol -> Siliguri -> Kolkata East Hub	7	MEDIUM	ACTIVE	4	8
528	1089	20 Hours	Lucknow Supply Center -> Gaya -> Asansol -> Kolkata East Hub	8	HIGH	ACTIVE	4	8
529	1103	20 Hours	Lucknow Supply Center -> Patna -> Prayagraj -> Kolkata East Hub	9	LOW	ACTIVE	4	8
530	1100	20 Hours	Lucknow Supply Center -> Varanasi -> Siliguri -> Kolkata East Hub	10	MEDIUM	ACTIVE	4	8
531	814	15 Hours	Lucknow Supply Center -> Pune Distribution Center (Direct Express)	1	MEDIUM	ACTIVE	5	8
532	818	15 Hours	Lucknow Supply Center -> Amravati -> Pune Distribution Center (Primary)	2	HIGH	ACTIVE	5	8
533	820	15 Hours	Lucknow Supply Center -> Nagpur -> Jabalpur -> Pune Distribution Center	3	LOW	ACTIVE	5	8
534	819	15 Hours	Lucknow Supply Center -> Bhopal -> Amravati -> Pune Distribution Center	4	MEDIUM	ACTIVE	5	8
535	846	16 Hours	Lucknow Supply Center -> Indore -> Nagpur -> Pune Distribution Center	5	HIGH	ACTIVE	5	8
536	845	16 Hours	Lucknow Supply Center -> Amravati -> Jabalpur -> Pune Distribution Center	6	LOW	ACTIVE	5	8
537	872	16 Hours	Lucknow Supply Center -> Nagpur -> Aurangabad -> Pune Distribution Center	7	MEDIUM	ACTIVE	5	8
538	911	17 Hours	Lucknow Supply Center -> Bhopal -> Nagpur -> Pune Distribution Center	8	HIGH	ACTIVE	5	8
539	906	17 Hours	Lucknow Supply Center -> Indore -> Jabalpur -> Pune Distribution Center	9	LOW	ACTIVE	5	8
540	933	17 Hours	Lucknow Supply Center -> Amravati -> Aurangabad -> Pune Distribution Center	10	MEDIUM	ACTIVE	5	8
541	579	11 Hours	Lucknow Supply Center -> Ahmedabad Trade Hub (Direct Express)	1	MEDIUM	ACTIVE	6	8
542	610	12 Hours	Lucknow Supply Center -> Jaipur -> Ahmedabad Trade Hub (Primary)	2	HIGH	ACTIVE	6	8
543	626	12 Hours	Lucknow Supply Center -> Indore -> Agra -> Ahmedabad Trade Hub	3	LOW	ACTIVE	6	8
544	611	12 Hours	Lucknow Supply Center -> Bhopal -> Jaipur -> Ahmedabad Trade Hub	4	MEDIUM	ACTIVE	6	8
545	660	13 Hours	Lucknow Supply Center -> Gwalior -> Indore -> Ahmedabad Trade Hub	5	HIGH	ACTIVE	6	8
546	641	12 Hours	Lucknow Supply Center -> Jaipur -> Agra -> Ahmedabad Trade Hub	6	LOW	ACTIVE	6	8
547	662	13 Hours	Lucknow Supply Center -> Indore -> Ajmer -> Ahmedabad Trade Hub	7	MEDIUM	ACTIVE	6	8
548	693	13 Hours	Lucknow Supply Center -> Bhopal -> Indore -> Ahmedabad Trade Hub	8	HIGH	ACTIVE	6	8
549	692	13 Hours	Lucknow Supply Center -> Gwalior -> Agra -> Ahmedabad Trade Hub	9	LOW	ACTIVE	6	8
550	710	13 Hours	Lucknow Supply Center -> Jaipur -> Ajmer -> Ahmedabad Trade Hub	10	MEDIUM	ACTIVE	6	8
551	394	8 Hours	Lucknow Supply Center -> Jaipur Regional Hub (Direct Express)	1	MEDIUM	ACTIVE	7	8
552	386	8 Hours	Lucknow Supply Center -> Ghaziabad -> Jaipur Regional Hub (Primary)	2	HIGH	ACTIVE	7	8
553	397	8 Hours	Lucknow Supply Center -> Kanpur -> Bhopal -> Jaipur Regional Hub	3	LOW	ACTIVE	7	8
554	414	8 Hours	Lucknow Supply Center -> Agra -> Ghaziabad -> Jaipur Regional Hub	4	MEDIUM	ACTIVE	7	8
555	428	9 Hours	Lucknow Supply Center -> Gwalior -> Kanpur -> Jaipur Regional Hub	5	HIGH	ACTIVE	7	8
556	447	9 Hours	Lucknow Supply Center -> Ghaziabad -> Bhopal -> Jaipur Regional Hub	6	LOW	ACTIVE	7	8
557	458	9 Hours	Lucknow Supply Center -> Kanpur -> Ajmer -> Jaipur Regional Hub	7	MEDIUM	ACTIVE	7	8
558	506	10 Hours	Lucknow Supply Center -> Agra -> Kanpur -> Jaipur Regional Hub	8	HIGH	ACTIVE	7	8
559	498	10 Hours	Lucknow Supply Center -> Gwalior -> Bhopal -> Jaipur Regional Hub	9	LOW	ACTIVE	7	8
560	522	10 Hours	Lucknow Supply Center -> Ghaziabad -> Ajmer -> Jaipur Regional Hub	10	MEDIUM	ACTIVE	7	8
\.


--
-- TOC entry 5088 (class 0 OID 16678)
-- Dependencies: 227
-- Data for Name: shipment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shipment (id, assigned_driver_id, assignment_status, current_path, notes, priority, route_nodes, route_status, status, route_id, transport_id, warehouse_id, active_route_option_id) FROM stdin;
10	HYD-5231	IN_PROGRESS	\N		express	Hyderabad Logistics Hub -> Warangal -> Nizamabad -> Chennai Port Warehouse	NORMAL	CREATED	85	8	2	\N
11	123	ASSIGNED	bangalore -> hyderabad		express	Bangalore Tech Hub -> Chennai -> Solapur -> Hyderabad Logistics Hub	REROUTED	CREATED	10	9	1	5
12	BAN-7342	IN_PROGRESS	bangalore -> hyderabad		critical	Bangalore Tech Hub -> Chennai -> Solapur -> Hyderabad Logistics Hub	REROUTED	CREATED	10	10	1	5
\.


--
-- TOC entry 5090 (class 0 OID 16685)
-- Dependencies: 229
-- Data for Name: transit_node; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transit_node (id, name, latitude, longitude) FROM stdin;
1	Mumbai	19.076	72.8777
2	Pune	18.5204	73.8567
3	Lonavala	18.7546	73.4062
4	Thane	19.2183	72.9781
5	Nagpur	21.1458	79.0882
6	Nasik	19.9975	73.7898
7	Aurangabad	19.8762	75.3433
8	Solapur	17.6599	75.9064
9	Amravati	20.9374	77.7796
10	Kolhapur	16.705	74.2433
11	Bangalore	12.9716	77.5946
12	Mysore	12.2958	76.6394
13	Hubli	15.3647	75.124
14	Mangalore	12.9141	74.856
15	Belgaum	15.8497	74.4977
16	Hyderabad	17.385	78.4867
17	Warangal	17.9689	79.5941
18	Nizamabad	18.6725	78.0941
19	Chennai	13.0827	80.2707
20	Coimbatore	11.0168	76.9558
21	Madurai	9.9252	78.1198
22	Salem	11.6643	78.146
23	Vellore	12.9165	79.1325
24	Kochi	9.9312	76.2673
25	Thiruvananthapuram	8.5241	76.9366
26	Kozhikode	11.2588	75.7804
27	Ahmedabad	23.0225	72.5714
28	Surat	21.1702	72.8311
29	Vadodara	22.3072	73.1812
30	Rajkot	22.3039	70.8022
31	Bhavnagar	21.7645	72.1519
32	Jaipur	26.9124	75.7873
33	Jodhpur	26.2389	73.0243
34	Udaipur	24.5854	73.7125
35	Ajmer	26.4499	74.6399
36	Bikaner	28.0229	73.3119
37	Lucknow	26.8467	80.9462
38	Kanpur	26.4499	80.3319
39	Agra	27.1767	78.0081
40	Varanasi	25.3176	82.9739
41	Prayagraj	25.4358	81.8463
42	Ghaziabad	28.6692	77.4538
43	Patna	25.5941	85.1376
44	Gaya	24.7914	85.0002
45	Kolkata	22.5726	88.3639
46	Asansol	23.6739	86.9524
47	Siliguri	26.7271	88.3953
48	Bhubaneswar	20.2961	85.8245
49	Cuttack	20.4625	85.883
50	Guwahati	26.1445	91.7362
51	Indore	22.7196	75.8577
52	Bhopal	23.2599	77.4126
53	Gwalior	26.2124	78.1772
54	Jabalpur	23.1815	79.9864
55	Hyderabad Logistics Hub	17.385	78.4867
56	Bangalore Tech Hub	12.9716	77.5946
57	Kolkata East Hub	22.5726	88.3639
58	Ahmedabad Trade Hub	23.0225	72.5714
59	Bhubaneswar	20.2961	85.8245
60	Prayagraj	25.4358	81.8463
61	Warangal	17.9784	79.5941
62	Cuttack	20.4625	85.883
63	Nizamabad	18.6725	78.0941
64	Pune Distribution Center	18.5204	73.8567
65	Jaipur Regional Hub	26.9124	75.7873
66	Warangal	17.9689	79.5941
\.


--
-- TOC entry 5092 (class 0 OID 16693)
-- Dependencies: 231
-- Data for Name: transport; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transport (id, current_location, current_route_id, transport_id, transport_status, driver_id) FROM stdin;
3	\N	\N	TRK-103	IN_TRANSIT	\N
4	\N	\N	TRK-104	IN_TRANSIT	\N
5	\N	\N	TRK-105	IN_TRANSIT	\N
6	\N	\N	TRK-106	IN_TRANSIT	\N
7	\N	\N	TRK-107	IN_TRANSIT	\N
8	\N	\N	TRK-108	IN_TRANSIT	\N
9	\N	\N	TRK-109	IN_TRANSIT	\N
10	\N	\N	TRK-110	IN_TRANSIT	\N
\.


--
-- TOC entry 5094 (class 0 OID 16700)
-- Dependencies: 233
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, username, password, role, name, warehouse_id, driver_id, email, pin, city, latitude, longitude) FROM stdin;
12	John Doe	\N	DRIVER	\N	\N	DRV-999	\N	$2a$10$Z/WJBkigZRs0uL88c.b.6OJ1sf3yE/Qlzty8sJ8JjDviGjE7WzM0y	Kolkata	22.5726	88.3639
13	drv	\N	DRIVER	\N	\N	drv666	\N	$2a$10$yOTkXewB8chO8RdnEspF8ubcNBgD0qO9QifvkdQ35yO/KSHcV39RO	Howrah	22.5958	88.2636
14	new drv	\N	DRIVER	\N	\N	drv876	\N	$2a$10$EiPpKyUegw10GdUwe4QsI.OKzS/rTnlnbg99heBcqdG1vs4nW5qwO	Mumbai	19.076	72.8777
15	high	\N	DRIVER	\N	\N	518	\N	$2a$10$MEfNjuoLzviYLjCuFhqARutM0JloOBV4P5356F.GQjCtsiOpScABK	Delhi	28.6139	77.209
16	arka	\N	DRIVER	\N	\N	123	\N	$2a$10$SQ4a0xHgHfZRFDd6u70i0ePbV/RVuH/ryGa/h8aVdfB.7/vRNFC6m	Bangalore	12.9716	77.5946
17	me	\N	DRIVER	\N	\N	564	\N	$2a$10$iUelKiMOeHC6JhGDLdp/W.pt49KstasyC8bHhx5YQ8MQ3nNio7DHe	Hyderabad	17.385	78.4867
18	ui	\N	DRIVER	\N	\N	09	\N	$2a$10$GpoRErNLNutkqIM6JvcfReJdCn9upr6hxTesqwRT3VHM/jHIrkDV6	Chennai	13.0827	80.2707
37	Test Driver	\N	DRIVER	\N	\N	DEBUG-001	\N	$2a$10$qohFhAS5HA9SHZZCUYw./uaNf/yWYillu95nTOnIl/pwiErCwXBtq	Mumbai	19.076	72.8777
30	dri(mumbai)	\N	DRIVER	\N	\N	003	\N	$2a$10$rHeRr5Yl2gQCCtBEiFbv4uVWiWtCgkHq/h4U2w5Tuvb.4ux9hjJsC	Mumbai	19.076	72.8777
31	dri(delhi)	\N	DRIVER	\N	\N	004	\N	$2a$10$x/Jy/96bFo82QfuPYGQ8XO6QxrDC41mKR4sna3KERVOO.MpDNTjMa	Delhi	28.6139	77.209
32	dri(bang)	\N	DRIVER	\N	\N	005	\N	$2a$10$3uzJ85Ufcg6l1X0Td/UwDe0PmErN6eN5fi1sTWnTdVC0PuRAV4MBq	Bangalore	12.9716	77.5946
33	dri(hyd)	\N	DRIVER	\N	\N	006	\N	$2a$10$s3sOJHN1Ub37fXKJbGvJwe2kbQKrziJ2eG6L46UwATgBPBi5.FxnK	Hyderabad	17.385	78.4867
34	dri(che)	\N	DRIVER	\N	\N	007	\N	$2a$10$YUmUSNGCdmrNyl3NLwqPnOFJ/EF1az5Rfql/1ckDVErzkNUkHEPVC	Chennai	13.0827	80.2707
36	dri(ahmd)	\N	DRIVER	\N	\N	009	\N	$2a$10$nK0neZqJATrZz.3LGKve0OdC62FR55DQX.Uyx7pExwbSsh7OnwB9e	Ahmedabad	23.0225	72.5714
35	dri(pune)	\N	DRIVER	\N	\N	008	\N	$2a$10$GuU5xTxrneOyBXyRhwQEF.S7NhJhMKqugoeXWOp5ACmG6V7bOGiIq	Pune	18.5204	73.8567
22	fd	\N	DRIVER	\N	\N	431	\N	$2a$10$xAAWHD0DrplDAlzBm7vv4uuhdZvq6hdkkP2nSkhNQxDbCycCtNJky	Pune	18.5204	73.8567
28	dri1	\N	DRIVER	\N	\N	001	\N	$2a$10$f2OMKW3SzAnL9eKpoGwfU./ySvzE76JELNv.mF5t0eVetxczAAvf6	Kolkata	22.5726	88.3639
29	dri2	\N	DRIVER	\N	\N	002	\N	$2a$10$7fGKzi23SbuYsdYuXLavs.cM3RSTwn3oCtpdQBjKX5kZib9M3VG.6	Mumbai	19.076	72.8777
38	notun 	\N	DRIVER	\N	\N	100	\N	$2a$10$VDIcpwl8zOiZK0cvLuXRU.InXifs52FMYPBo/MFDOs4YE3TWLzJLy	Mumbai	19.076	72.8777
39	Subagent Test	\N	DRIVER	\N	\N	SUB-101	\N	$2a$10$sEePtuIi1g.3i45j0gc1uuESeHoVl/QXUajbG7A3Id.zZlH7ETyC2	Kolkata	22.5726	88.3639
40	der	\N	DRIVER	\N	\N	101	\N	$2a$10$ULaZ3yhA7g0Jli0eWZJlDuYQ/NIKo.ms6D8PKvQtCJLpQSO/BBm0K	Bangalore	12.9716	77.5946
42	honey singh	\N	DRIVER	\N	\N	vol-1	\N	$2a$10$52uNPjUruM1hYgkPlL7yVObiTyCk3T1C9cMwLPN.B4EW5lGxQjEGW	Durgapur	23.5204	87.3119
44	dsoumi192@gmail.com	\N	DRIVER	\N	\N	DUR-7987	\N	$2a$10$n6riYDx8EkTZL8LXgDQK8ObG2AKEKOK9MrS5IKg.ruBZbg1IwWUCu	Durgapur	23.5204	87.3119
46	Raju	\N	DRIVER	\N	\N	AHM-2314	\N	$2a$10$3ahuDPAX7MlIp7m/lURzk.8T4Fj28je0x3g6d1u87T74xcaiHFt3S	Ahmedabad	23.0225	72.5714
47	Puchu	\N	DRIVER	\N	\N	HYD-9593	\N	$2a$10$w4Bypb.4oq7BJQuBvW/nFOQWh9FhGqwEelQKerlM.yYU81Xd1uFeS	Hyderabad	17.385	78.4867
48	Raja	\N	DRIVER	\N	\N	HYD-6262	\N	$2a$10$nIjLRu/0r5OoIq.21mTIaeE8dZ4Yo.Qqr1rfXmTPZUJGwRwstTR5W	Hyderabad	17.385	78.4867
49	Abhi	\N	DRIVER	\N	\N	HYD-3593	\N	$2a$10$PJ.wntXLOWWi0zcj950PL.BO3qzwh43KnZq7Szqk4gL0nKNOqIeei	Hyderabad	17.385	78.4867
51	Soumi	$2a$10$LE8hSLH6qkN6phM2rbYPH.nRDdzpF3Wk09GaGaDO70hp8g4XXBgsC	ADMIN	\N	2	\N	dsoumi192@gmail.com	\N	\N	\N	\N
52	kujo	\N	DRIVER	\N	\N	HYD-5231	\N	$2a$10$Mpj5DTdT8.IyK8hCuxdp0uwyPCNUdS.4Ak8TTsPkmRnWlGX.Mzq/a	Hyderabad	17.385	78.4867
53	Sudipta	$2a$10$JX0LsK97YS/AxyP42staMO8Z7vKlkzfxexRzIDsSqJ6jv6hyx4Mpe	ADMIN	\N	1	\N	sudipta03@gmail.com	\N	\N	\N	\N
54	kaju	\N	DRIVER	\N	\N	BAN-7342	\N	$2a$10$4HG2iaPoZ/k69L9XmfFfGOpfpXEN5yTAabR327N8PPY8lJXXzVbn2	Bangalore	12.9716	77.5946
\.


--
-- TOC entry 5096 (class 0 OID 16707)
-- Dependencies: 235
-- Data for Name: warehouse; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.warehouse (id, name, city, latitude, longitude, admin_user_id) FROM stdin;
3	Chennai Port Warehouse	Chennai	13.0827	80.2707	\N
4	Kolkata East Hub	Kolkata	22.5726	88.3639	\N
7	Jaipur Regional Hub	Jaipur	26.9124	75.7873	\N
8	Lucknow Supply Center	Lucknow	26.8467	80.9462	\N
6	Ahmedabad Trade Hub	Ahmedabad	23.0225	72.5714	\N
5	Pune Distribution Center	Pune	18.5204	73.8567	\N
2	Hyderabad Logistics Hub	Hyderabad	17.385	78.4867	51
1	Bangalore Tech Hub	Bangalore	12.9716	77.5946	53
\.


--
-- TOC entry 5106 (class 0 OID 0)
-- Dependencies: 220
-- Name: alert_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.alert_id_seq', 20, true);


--
-- TOC entry 5107 (class 0 OID 0)
-- Dependencies: 222
-- Name: driver_location_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.driver_location_id_seq', 37, true);


--
-- TOC entry 5108 (class 0 OID 0)
-- Dependencies: 224
-- Name: route_option_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.route_option_id_seq', 5, true);


--
-- TOC entry 5109 (class 0 OID 0)
-- Dependencies: 226
-- Name: routes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.routes_id_seq', 560, true);


--
-- TOC entry 5110 (class 0 OID 0)
-- Dependencies: 228
-- Name: shipment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shipment_id_seq', 12, true);


--
-- TOC entry 5111 (class 0 OID 0)
-- Dependencies: 230
-- Name: transit_node_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transit_node_id_seq', 66, true);


--
-- TOC entry 5112 (class 0 OID 0)
-- Dependencies: 232
-- Name: transport_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transport_id_seq', 1, false);


--
-- TOC entry 5113 (class 0 OID 0)
-- Dependencies: 234
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 54, true);


--
-- TOC entry 5114 (class 0 OID 0)
-- Dependencies: 236
-- Name: warehouse_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.warehouse_id_seq', 8, true);


--
-- TOC entry 4903 (class 2606 OID 16721)
-- Name: alert alert_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.alert
    ADD CONSTRAINT alert_pkey PRIMARY KEY (id);


--
-- TOC entry 4905 (class 2606 OID 16723)
-- Name: driver_location driver_location_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.driver_location
    ADD CONSTRAINT driver_location_pkey PRIMARY KEY (id);


--
-- TOC entry 4907 (class 2606 OID 16725)
-- Name: route_option route_option_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route_option
    ADD CONSTRAINT route_option_pkey PRIMARY KEY (id);


--
-- TOC entry 4909 (class 2606 OID 16727)
-- Name: routes routes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.routes
    ADD CONSTRAINT routes_pkey PRIMARY KEY (id);


--
-- TOC entry 4911 (class 2606 OID 16729)
-- Name: shipment shipment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shipment
    ADD CONSTRAINT shipment_pkey PRIMARY KEY (id);


--
-- TOC entry 4913 (class 2606 OID 16731)
-- Name: transit_node transit_node_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transit_node
    ADD CONSTRAINT transit_node_pkey PRIMARY KEY (id);


--
-- TOC entry 4915 (class 2606 OID 16733)
-- Name: transport transport_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transport
    ADD CONSTRAINT transport_pkey PRIMARY KEY (id);


--
-- TOC entry 4917 (class 2606 OID 16735)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 4919 (class 2606 OID 16737)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4921 (class 2606 OID 16739)
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- TOC entry 4923 (class 2606 OID 16741)
-- Name: warehouse warehouse_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse
    ADD CONSTRAINT warehouse_pkey PRIMARY KEY (id);


--
-- TOC entry 4925 (class 2606 OID 16742)
-- Name: routes fk9dkpt9ubpy2522aprdvfe7r5q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.routes
    ADD CONSTRAINT fk9dkpt9ubpy2522aprdvfe7r5q FOREIGN KEY (source_id) REFERENCES public.warehouse(id);


--
-- TOC entry 4924 (class 2606 OID 16747)
-- Name: route_option fk9vx32w36l6nkhmih0vyqwcmcv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.route_option
    ADD CONSTRAINT fk9vx32w36l6nkhmih0vyqwcmcv FOREIGN KEY (alert_id) REFERENCES public.alert(id);


--
-- TOC entry 4932 (class 2606 OID 16782)
-- Name: warehouse fk_warehouse_admin; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warehouse
    ADD CONSTRAINT fk_warehouse_admin FOREIGN KEY (admin_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 4930 (class 2606 OID 16752)
-- Name: transport fkdx1njcsptvsv77lcubduss848; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transport
    ADD CONSTRAINT fkdx1njcsptvsv77lcubduss848 FOREIGN KEY (driver_id) REFERENCES public.users(id);


--
-- TOC entry 4927 (class 2606 OID 16757)
-- Name: shipment fke3q06p1gkss72fquqabyqjfqw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shipment
    ADD CONSTRAINT fke3q06p1gkss72fquqabyqjfqw FOREIGN KEY (transport_id) REFERENCES public.transport(id);


--
-- TOC entry 4928 (class 2606 OID 16762)
-- Name: shipment fkghw3j6lueyw6i2udq0973yg1j; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shipment
    ADD CONSTRAINT fkghw3j6lueyw6i2udq0973yg1j FOREIGN KEY (route_id) REFERENCES public.routes(id);


--
-- TOC entry 4926 (class 2606 OID 16767)
-- Name: routes fkle8gn57caqxgctaf00h4f6smd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.routes
    ADD CONSTRAINT fkle8gn57caqxgctaf00h4f6smd FOREIGN KEY (destination_id) REFERENCES public.warehouse(id);


--
-- TOC entry 4929 (class 2606 OID 16772)
-- Name: shipment fko086vq2dhtvxyq3udcblrr2pp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shipment
    ADD CONSTRAINT fko086vq2dhtvxyq3udcblrr2pp FOREIGN KEY (warehouse_id) REFERENCES public.warehouse(id);


--
-- TOC entry 4931 (class 2606 OID 16777)
-- Name: users users_warehouse_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouse(id);


-- Completed on 2026-04-23 21:33:31

--
-- PostgreSQL database dump complete
--

\unrestrict WFthLd5e1ujJg5waMlCqdASOfdeACEYJsp36vmMNd1IzO9KabO5v8GixURuGX2C

