server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d7n4fpho3t8c73efo4c0-a.singapore-postgres.render.com/supply_chain_db_fy1l?sslmode=require
spring.datasource.username=supply_chain_db_fy1l_user
spring.datasource.password=2VlPygnYXRueBpMwaZrPpdKy3LnndZiq
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.user.name=disabled
spring.security.user.password=disabled
